# 평가자 gold 라벨링 (실제 시트 질문 64개 · 길이 상위 50%)

각 블록의 **gold:** 칸에 정답 verdict를 적으세요. **모델 판정이 맞으면 비워두면** 됩니다(빈칸=동의). 판단이 어려우면 `?` 로 두세요(측정에서 제외).

**verdict 뜻**
- `answerable`     : 봇이 위키 자료로 질문의 **핵심을 사실로 답변** 가능
- `opinion-grounded`: 관련 사실은 있으나 질문이 **의견·제안·평가·진단**을 요구(그 판단은 자료에 없음)
- `external-needed` : 답하려면 **타기관 비교·외부 순위·뉴스** 등 서울대 자체 기록 밖 정보 필요
- `internal-gap`    : 질문 **주제 자체가 서울대 자료에 없음**(진짜 공백)

> 코퍼스를 외울 필요 없습니다. **질문 성격 + 아래 "실제 답변" + 평가자 근거**만 보고 판단하세요.

---

## [1] 모델: `answerable`  ·  105자 · tier1 · 위키: plan, vision, history, status, finance, board

**Q:** 총장이 사용할 수 있는 예산을 늘릴 방법은 1) 정부 출연금 증가, 2) 기부금 유치, 3) 연구비 수주 독려 이렇게 3개 인가? 그 외 총장이 사용할 수 있는 예산을 늘릴 방법은 없을까?

**평가자 aspect 판정:**
  - 현재 총장이 사용할 수 있는 예산 확보 방법 3가지(정부출연금·기부금·연구비)의 타당성 **[yes]**
  - 질문에서 제시한 3가지 외 추가적인 예산 확보 방법의 존재 여부 **[yes]**
  - 각 방법별 구체적 규모·전략·추진현황 **[partial]**
  - 향후 잠재력 있는 신규 재원 개발 방안의 전략적 평가 **[partial]**

**부족(missing):** 각 재원별 2026년 목표액·실제 규모 비교분석 · 신규 재원(예: 부동산 임대료·자회사 수익)의 재무적 기여도 정량화

**실제 봇 답변(발췌):**
> # 신임 총장의 가용 예산 확대 전략 — 전체 경로 분석
> 
> ---
> 
> ## 🔑 핵심 결론
> 
> > 제시하신 3가지(정부출연금·기부금·연구비)는 **주요 경로이지만 전부가 아닙니다.**
> > 자료를 종합하면 **총 7개 범주, 15개 이상의 구체적 경로**가 확인됩니다.
> 
> ---
> 
> ## 📊 재원 확대 경로 전체 지도
> 
> | 범주 | 경로 | 현재 규모(2024) | 확대 가능성 |
> |---|---|---:|---|
> | ① 정부출연금 | 기본출연금·특별회계 | 6,229억 | 중 |
> | ② 기부금 | 발전재단 모금 | 944억 | 중~고 |
> | ③ 연구비 수주 | 산학협력단 간접비 | 8,322억(산학 전체) | 고 |
> | ④ **수익사업** | SNU홀딩스·기술지주 | 초기 단계 | 중장기 |
> | ⑤ **자산 운용** | 부동산·OCIO | 제한적 | 중 |
> | ⑥ **예산 내부 재배분** | 성과연동·적
>   […중략…]
>   산안 이미 상당 부분 고착 지적 | [평의원회] 19기-4차 |
> 
> > **결론**: 총장이 예산을 늘리는 경로는 3가지가 아니라 **7개 범주**입니다. 단기적으로는 **기부금+내부 재배분+연구 간접비**, 중장기적으로는 **수익사업+자산운용+학교채**가 핵심 추가 경로입니다. 특히 **학교채 발행**과 **SNU홀딩스 수익사업**은 기존 3가지에 없는 구조적 재원 확대 수단으로 제도 기반이 갖춰질 경우 가장 큰 규모의 재원 확보가 가능합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [2] 모델: `answerable`  ·  55자 · tier1 · 위키: senate, board, vision, status, history

**Q:** 가장 최근 이슈면 평의원회 7,8차 자료들이 나와야하는거 아니니? 그런 자료 내용은 왜 하나도 없니

**평가자 aspect 판정:**
  - 평의원회 7차, 8차 회의 자료의 존재 여부 **[yes]**
  - 평의원회 7차, 8차 회의 내용(주요 안건, 심의 결과 등) **[yes]**
  - 왜 컨텍스트에 이 자료들이 포함되지 않았는지에 대한 설명 **[no]**

**부족(missing):** 자료가 위키에 누락된 이유에 대한 설명 또는 편집자의 의도

**실제 봇 답변(발췌):**
> 맞습니다. 지적이 정확합니다. 죄송합니다.
> 
> 이번에 제공된 위키 자료에는 **19기 7차(2026-04-16)** 와 **18기 8차(2024-06-20)** 회의록이 포함되어 있는데, 이전 답변에서 이를 제대로 반영하지 못했습니다. 제공된 자료 기준으로 **가장 최근 회의인 19기 7차**를 중심으로 다시 정리합니다.
> 
> ---
> 
> # 평의원회 최근 이슈 Top 10 (자료 기준 최신순)
> 
> ---
> 
> ## 📋 19기 7차 본회의 (2026-04-16) — 최신 회의
> 
> **1. 글로벌인재학부 모집단위 신설 — 8차 서면심의 이월**
> 신설 목적·기대효과 불명확, 국제화지수·재정 효과 실질성 질의, 전임교원 의견 수렴 미흡 지적. 기존 장기발전계획(국제학부 신설+복수 트랙)과 현 추진안(특정 트랙) 간 차이도 문제 제기. 외국인 학생 한국어 교육 모델·인프라(공간·지도교수·기숙사) 검토 필요 의견까지 나
>   […중략…]
>   **10. 인권센터 규정 전부개정 — 학생 사건 시 학생 위촉 조항 신설**
> 이준정 인권센터장 발제. **학생 사건 발생 시 학생을 위원으로 위촉**하고 사전 교육을 실시하는 내용이 핵심. [평의원회] 18기-8차
> 
> ---
> 
> > 💡 **19기 7차의 글로벌인재학부·양자물질연구소·총장추천위원회 안건**은 모두 8차 서면심의로 이월된 상태로, 8차 결과가 현재 가장 주목할 후속 이슈입니다. 해당 안건에 대해 더 자세히 알고 싶으시면 말씀해 주세요.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [3] 모델: `answerable`  ·  34자 · tier1 · 위키: senate, plan, board, status, yhl-speeches, history

**Q:** AI 대학원 설립 추진 경과와 의결 사항을 시간순으로 정리해줘

**평가자 aspect 판정:**
  - AI 대학원 설립 추진의 시작 시점 및 초기 논의 **[partial]**
  - AI 대학원 설립 관련 평의원회 검토·심의 과정 (회의별 진행상황) **[yes]**
  - AI 대학원 설립 관련 최종 의결 및 결정 사항 **[partial]**
  - AI 대학원의 구체적 설립 계획 내용 (목표·구조·일정 등) **[partial]**

**부족(missing):** AI 대학원 설립 최초 논의 시점 (언제부터 추진되었는지) · 설립 준비단 구성 이후 구체적 진행 현황 (19기-7차 이후) · 최종 의결 완료 여부 및 시점

**실제 봇 답변(발췌):**
> # AI 대학원 설립 추진 경과 (시간순)
> 
> ## 📋 추진 경과 한눈에 보기
> 
> | 시점 | 기구 | 내용 | 결과 |
> |---|---|---|---|
> | 2026.1.2 | 총장 신년사 | AI 대학원 설립 공식 예고 | 선언 |
> | 2026년 초 | 대학운영계획 | 2026년 핵심 실행과제로 지정 | 계획 확정 |
> | 2026.3.19 | 평의원회 5차 | AI 대학원 설립계획(안) 원안 검토 | 검토 (미최종심의) |
> | 2026.3.24 | 이사회 2차 | AI 대학원 설립계획(안) 보고 | 보고 접수 |
> | 2026.4.16 | 평의원회 7차 | AI 대학원 설립계획(안) 원안 심의 | 심의 완료 |
> 
> ---
> 
> ## 1️⃣ 2026.1.2 — 총장 신년사: 공식 예고
> 
> 유홍림 총장이 2026년 신년사에서 AI 대학원 설립을 처음 공식 선언했습니다 [유홍림총장연설] 신년사-2026.
> 
> > 
>   […중략…]
>   일정 [대학운영계획] 2026-운영계획-실행과제11
> 
> ---
> 
> ## ⚠️ 쟁점 및 향후 과제
> 
> 평의원회 7차 심의에서 도출된 주요 후속 과제 [평의원회] 19기-7차:
> 
> - **융합과학기술대학원 등 기존 조직과의 역할 중복·교원 이탈** 문제 해소 방안 마련
> - **개방형 플랫폼** 운영 방식 구체화
> - **거버넌스 체계** 확정 및 설립 준비단 구성
> - **2027년 개원** 목표를 위한 후속 행정 절차 이행 [유홍림총장연설] 신년사-2026

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [4] 모델: `answerable`  ·  31자 · tier1 · 위키: plan, board, senate, history, vision, status

**Q:** 서울대학교의 비교과 교육 프로그램에는 어떤 것들이 있나?

**평가자 aspect 판정:**
  - 서울대의 비교과 교육 프로그램의 종류·유형 **[yes]**
  - 각 비교과 프로그램의 구체적 내용·운영 방식 **[partial]**
  - 비교과 프로그램의 참여 대상·규모·성과 **[partial]**

**부족(missing):** (없음)

**실제 봇 답변(발췌):**
> # 서울대학교 비교과 교육 프로그램 현황
> 
> 서울대학교의 비교과 교육 프로그램은 **융합교육·창의역량**, **공동체·글로벌역량**, **연구역량**, **문화예술**, **사회공헌·나눔** 등 다양한 축으로 운영되고 있습니다.
> 
> ---
> 
> ## 🔬 연구·탐구역량 강화
> 
> | 프로그램 | 주요 내용 |
> |---|---|
> | 학부생 연구인턴십 | 학내 대학원 연구실 + 교외 산업기관 인턴십 [대학운영계획] 2026-섹션3-추진성과및기본방향 |
> | 첨단융합학부 비교과 | 첨단분야 전문가 특강, 현장문제해결형, 시그니처 강연, 해외현장학습 [대학운영계획] 2026-섹션3-추진성과및기본방향 |
> | 학생자율연구 비교과 | 학부대학·인문대·자유전공학부·사회대·기초과학공동기기원 등 5개 유형 운영 [대학운영계획] 2026-운영계획-실행과제3 |
> | 학생 연구성과 발표 | 온·오프라인 동시 paper present
>   […중략…]
>   운영계획] 2026-운영계획-실행과제1 |
> | AI/컴퓨팅 프로젝트 경진대회 | 컴퓨팅 교과목 이수 학생 대상, 전공분야·실생활 주제 프로젝트 (2학기 개최) [대학운영계획] 2026-운영계획-실행과제3 |
> 
> ---
> 
> > **참고**: 비교과 프로그램의 공통 과제로 **첨단융합학부 비교과 참여율 제고**(일부 학생 집중 현상 해소, 이수인증서 도입 검토)가 개선 필요 사항으로 언급되고 있습니다 [대학운영계획] 2026-섹션3-추진성과및기본방향.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [5] 모델: `answerable`  ·  28자 · tier1 · 위키: senate, board, vision, history, status, plan

**Q:** 시수 유연화에 대한 논의에 대한 근거 자료가 있나?

**평가자 aspect 판정:**
  - 시수 유연화의 정의 및 내용 **[partial]**
  - 시수 유연화에 대한 논의 기록(회의·위원회·정책연구 등) **[yes]**
  - 시수 유연화의 배경·목적·추진 현황 **[partial]**
  - 시수 유연화에 대한 평가·입장·제안 **[partial]**

**부족(missing):** 시수 유연화의 정확한 정의 및 구체적 내용 · 시수 유연화 도입의 전체 추진 일정 및 현황 · 시수 유연화에 대한 상세한 쟁점 분석

**실제 봇 답변(발췌):**
> ## 전임교원 시수 유연화 관련 논의
> 
> 제공된 위키 자료 전체를 검토한 결과, **"시수 유연화"**를 직접적으로 다루는 근거 자료는 포함되어 있지 않습니다.
> 
> 다만, 교원 제도 유연화와 관련하여 **간접적으로 연결될 수 있는 논의**는 다음과 같이 확인됩니다.
> 
> ---
> 
> ### 🎓 교원 소속 및 역할의 유연화 논의
> 
> - 2024년 학칙 개정을 통해 **"융복합 역량 강화를 위한 교원의 소속 유연화"** 가 반영되었습니다 [이사회] 2024-1차. 교원이 복수 단위에 소속될 수 있는 제도적 기반이 마련된 것으로, 담당 교과목 범위와 간접적으로 연관될 수 있습니다.
> 
> - 중장기발전계획에서는 **"트랙별 연구평가 제도"** (연구·교육·행정 트랙 분리) 도입을 방향으로 제시하고 있어 [중장기발전계획] 중장기-제2장-연구, 교원별 교육 부담의 차등화 가능성을 시사합니다.
> 
> - 같은 맥락에서 **"새로운 형태의 교원 임용"** 도 7대 핵심과제 중 하나로 명시되어 있습니다 [중장기발전계획] 중장기-제1장.
> 
> ---
> 
> ### ⚠️ 한계
> 
> 시수 유연화를 **직접 의제로 다룬 평의원회·이사회 회의록**이나 **관련 규정 개정안**은 현재 제공된 자료 범위 내에 포함되어 있지 않습니다. 해당 주제에 대한 구체적 논의 내용은 교무처 내부 자료나 별도 위원회 회의록을 통해 확인하시기 바랍니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [6] 모델: `answerable`  ·  28자 · tier1 · 위키: board, vision, status, senate, history

**Q:** 이사회가 주로 다루는 안건을 어떤 것들이 있습니까?

**평가자 aspect 판정:**
  - 이사회가 다루는 주요 안건 유형 **[yes]**
  - 구체적인 안건 사례 및 내용 **[yes]**

**부족(missing):** (없음)

**실제 봇 답변(발췌):**
> # 이사회 주요 안건 유형 분석
> 
> ## ⚖️ 법적 근거
> 
> 이사회는 **정관 변경·예산·결산·재산취득·처분·임원 선임 등 법인 핵심 사항**을 심의·의결하는 국립대학법인 서울대학교 최고 의사결정기구입니다. [이사회] entity
> 
> ---
> 
> ## 📋 안건 유형별 분류
> 
> ### 💰 1. 예산·결산·재정
> 
> | 안건 | 시기 | 출처 |
> |---|---|---|
> | 2023년도 예산 의결 | 2023-2차 | [이사회] 2023-2차 |
> | 2024년도 예산 의결 (1조 563억) | 2024-1차 | [이사회] 2024-1차 |
> | 2025년도 예산 의결 (1조 1,223억) | 2025-1차 | [이사회] 2025-1차 |
> | 2026년도 예산 의결 (1조 2,038억) | 2026-1차 | [이사회] 2026-1차 |
> | 2022년 법인회계 결산 (세입 10,464억, 세출 9,973억) | 202
>   […중략…]
>   25-8차 |
> | 총장선출제도 개선 논의 | [이사회] 2025-8차, 2026-2차 |
> 
> ---
> 
> ## 🔍 종합 시사점
> 
> 중장기발전계획은 **"학사운영 관련 일부 기능을 대학본부·평의원회·학사위원회에 위임하고, 이사회 구성의 다양성을 확보"** 하는 방향을 제시하고 있어 [중장기발전계획] 중장기-제2장-운영체제, 현재 이사회가 학칙·인사 등 광범위한 안건을 다루는 구조에서 점차 **법인 핵심 사항 중심으로 역할이 재편**될 가능성이 있습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [7] 모델: `answerable`  ·  27자 · tier1 · 위키: senate, board, status, finance

**Q:** 평의원회 19기 4차 5차 6차 파일에 있지않아?

**평가자 aspect 판정:**
  - 평의원회 19기 4차 회의록 존재 여부 **[yes]**
  - 평의원회 19기 5차 회의록 존재 여부 **[yes]**
  - 평의원회 19기 6차 회의록 존재 여부 **[partial]**

**부족(missing):** 19기 6차 회의의 상세 내용(서면심의로 진행된 것으로만 언급됨)

**실제 봇 답변(발췌):**
> # 제19기 평의원회 4·5·6차 본회의 회의 기록
> 
> 제공된 위키 자료에 19기 4차, 5차, 6차(서면심의) 자료가 **모두 포함**되어 있습니다. 아래에 정리합니다.
> 
> ---
> 
> ## 🗳️ 제19기 제4차 본회의
> 
> > **회의일**: 2026-02-05 (목) 16:00~18:30 / 행정관 405호 / 참석: 32/49명 [[19기-4차]]
> 
> ### 보고 안건
> | 안건 | 발제자 | 결과 |
> |---|---|---|
> | 전임교원 책임시수 관리체계 개선(안) | [[안동환]] 교무처장 | 원안 접수 |
> 
> **주요 쟁점** [[19기-4차]]:
> - 시행 과정 문제를 교육 단위가 자체 해결하기에 한계 → **시간강사료 예산 지원 확대** 필요 의견
> - 제3조제1항제2호: **출산휴가 기간도 산입 제외** 필요 → 교무처 검토 답변
> 
> ---
> 
> ### 심의 안건
> | 안건 | 발제자 | 결과 |
> |--
>   […중략…]
>    "공모전은 전 학문 분야 참여 가능" → **관련 조문 보완을 위해 [[19기-6차서면심의]]로 재심의**
> 
> ---
> 
> ### 자체 안건
> - **총장추천위원회 위원 선출 관련 논의** — 별다른 의견 없음 [[19기-5차]]
> 
> ---
> 
> ## 🗳️ 제19기 제6차 본회의 (서면심의)
> 
> > **형식**: 서면심의 (대면 본회의 없음) [[19기-6차서면심의]]
> 
> ### 배경
> 제5차 본회의 종료 후 **미래연구진흥센터 기능 관련 일부 내용 정정 사항

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [8] 모델: `opinion-grounded`  ·  204자 · tier1 · 위키: senate, vision, board, status, history

**Q:** 시흥캠퍼스 관련 안건은 병원·체육관·재외동포센터·송전선로·풍동센터 등 물리적 인프라 구축이 핵심인데, 이런 물리적 인프라 구축 계획은 어떤 원칙, 계획 등에 기반해 있나? 서울캠퍼스와 시흥캠퍼스의 관계 설정, 역할 분담, 시흥캠퍼스의 주요 기능 등 보다 일반적 플랜에 기반해 인프라 구축이 계획된 것인지, 아니면 현실적 고려에 의해 임의적, 산발적인 성격이 있는가?

**평가자 aspect 판정:**
  - 시흥캠퍼스 물리적 인프라 구축의 상위 계획·원칙·전략적 기초 **[partial]**
  - 서울캠퍼스와 시흥캠퍼스의 관계 설정, 역할 분담, 기능 정의 **[no]**
  - 시흥캠퍼스 인프라 구축이 일관된 장기계획 vs 현실적 필요에 따른 임의적 성격의 판단·평가 **[partial]**
  - 병원·체육관·재외동포센터·송전선로·풍동센터 등 구체 인프라 구축 결정 근거 및 우선순위 원칙 **[no]**

**부족(missing):** 서울캠퍼스와 시흥캠퍼스의 명시적 역할 분담·기능 정의 · 인프라 구축 우선순위 기준·원칙 · 병원·체육관·풍동센터 등 개별 사업 선정·배치의 전략적 근거

**실제 봇 답변(발췌):**
> ## 🏗️ 시흥캠퍼스 인프라 구축의 계획성 vs. 산발성 분석
> 
> 결론부터 말하면, **상위 전략 플랜은 존재하나 실제 인프라 구축은 마스터플랜과의 정합성이 확보되지 않은 채 개별 사업이 선행된 측면이 강하다**는 것이 자료에서 읽히는 그림입니다.
> 
> ---
> 
> ## 📋 존재하는 상위 계획들
> 
> ### 1. 「2021~2025 시흥캠퍼스 2단계 종합발전계획」
> 
> 2022년 6월 평의원회에 보고된 계획으로, 김규홍 시흥캠퍼스본부장이 발제했습니다 [평의원회] 17기-8차. 이 계획이 이후 치과병원 건립(17기-11차), 배곧병원 토지이전(17기-12차) 등 개별 사업으로 연결되는 **상위 근거 문서**로 제시됩니다. 그러나 평의원회 자료에는 이 계획의 구체적 내용(캠퍼스 역할 설정, 기능 배분 원칙 등)은 수록되어 있지 않습니다.
> 
> ### 2. 중장기발전계획(2022~2040)의 멀티캠퍼스 전략
> 
> 2040 
>   […중략…]
>   |
> | 거버넌스 안정성 | ❌ 전담 위원회 폐지로 오히려 약화 |
> | 외부 주도 사업 비중 | ⚠️ 높음 — 국가 공모·지자체 주도 사업에 부지 제공 방식 다수 |
> 
> 자료의 범위 내에서 확인된 내용만을 기준으로 할 때, **시흥캠퍼스 인프라 구축은 중장기적 비전과 원칙이 문서로는 존재하나, 실행 단계에서는 마스터플랜이 뒤따라가는 구조** 속에서 외부 기회와 현실적 필요에 의해 개별 사업이 순차적으로 축적되는 패턴을 보인다고 평가할 수 있습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [9] 모델: `opinion-grounded`  ·  200자 · tier1 · 위키: senate, board, finance, vision, plan, status, history

**Q:** 간호대학은 2030년 무렵에 연건캠퍼스에서 관악캠퍼스의 공대로 이전해. 간호대가 이전하면서 낙성대 근처의 유휴 부지에 요양시설을 짓고 서울대 구성원 및 지역사회 주민의 고령화 시대 수요에 맞는 서비스를 제공하는 방안은 가능할까? 요양시설과 함께 호스피스 병동, 그리고 서울대 장례식장, 서울대 공원 수목장 묘지를 하나의 패키지로 엮어서 제공하는 건 가능할까?

**평가자 aspect 판정:**
  - 간호대학 2030년 무렵 연건캠퍼스에서 관악캠퍼스(공대) 이전 계획의 존재 여부 **[no]**
  - 낙성대 근처 유휴 부지에 요양시설·호스피스 병동·장례식장·수목장 묘지 등 복합시설 조성의 가능성 또는 계획 **[no]**
  - 서울대 구성원·지역사회 고령화 대응 의료/복지 서비스 제공 계획 또는 전략 **[partial]**
  - 위 시설들을 패키지로 통합 제공하는 구체적 추진 가능성 또는 실행 전략 **[no]**

**부족(missing):** 간호대학 이전 계획 (연건→관악) · 낙성대 근처 부지 활용 계획 · 요양시설·호스피스·장례식장·수목장 복합시설 조성 계획 · 고령화 대응 의료복지 패키지 사업 전략 · 서울대 자체 장례식장·수목장 묘지 설립 계획

**실제 봇 답변(발췌):**
> # 간호대학 이전 후 연건캠퍼스 활용 — 요양·호스피스·장례 복합시설 가능성 분석
> 
> ---
> 
> ## 🔑 핵심 결론 먼저
> 
> > **제공된 자료에는 간호대학의 연건→관악 이전 계획, 이전 시기(2030년), 연건캠퍼스 유휴 부지 활용 방안에 대한 직접적 자료가 없습니다.** 다만 서울대의 캠퍼스 전략, 자산 운용, 거버넌스 구조, 재정 전략 자료를 바탕으로 **아이디어의 실현 가능성과 구조적 장애물**을 분석할 수 있습니다.
> 
> ---
> 
> ## 📍 연건캠퍼스의 현재 위상 — 자료 기반
> 
> | 항목 | 내용 |
> |---|---|
> | 부지 면적 | **94천㎡** (관악 4,108천㎡의 약 2.3%) [대학현황 fact](/wiki?agent=status&type=facts&id=%ED%98%84%ED%99%A9.fact) |
> | 성격 | 의대·치대·간호대·서울대병원 밀집 의학 특화 캠퍼스 |
> | 핵심 문제 
>   […중략…]
>    실적**으로 활용 가능
> 
> ---
> 
> ## ⚠️ 분석의 한계
> 
> **간호대학 이전 계획, 이전 후 연건캠퍼스 유휴 공간 규모, 서울대병원과의 협력 현황**에 대한 직접 자료가 제공된 위키에 포함되어 있지 않습니다. 또한 연건캠퍼스의 정확한 용도지역, 서울시 도시계획 제한 조건에 대한 별도 조사가 필요합니다. 수목장의 경우 관악수목원 활용이 연건캠퍼스 패키지보다 현실적이나, 두 입지를 하나의 브랜드로 통합하는 방안의 타당성 검토가 선행되어야 합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [10] 모델: `opinion-grounded`  ·  182자 · tier1 · 위키: senate, board, finance, vision, plan, history, status

**Q:** 서울대의 부동산 자산에 대해 이야기할게. 다른 학교나 서울대병원은 서울 도심의 건물을 사고 있어. 하지만 서울대는 도심 건물을 샀는지 모르겠어. 서울대학교 치의학대학원이 건물 건축으로 혜화 로터리의 서울여대 건물을 임차하고 있는데 이 비용이면 대출 끼고 건물을 살 수도 있을 것 같아. 서울대는 왜 도심 부동산을 안사는 거지?

**평가자 aspect 판정:**
  - 서울대의 도심 부동산(건물) 매입 현황 및 정책 **[no]**
  - 다른 대학(카이스트 등)이나 서울대병원의 도심 부동산 매입 사례 **[no]**
  - 치의학대학원의 혜화 로터리 건물 임차 비용 및 재정 영향 **[partial]**
  - 서울대가 부동산 구매가 아닌 임차 방식을 선택하는 이유(의도, 전략, 재정 정책) **[no]**

**부족(missing):** 서울대 도심 부동산 구매 사례 및 현황 · 타 대학/서울대병원의 도심 부동산 매입 사례 · 치의학대학원 혜화 로터리 임차료 구체적 금액 · 서울대의 부동산 취득 정책·전략·의사결정 근거 · 매입 대신 임차를 선택한 재정적·정책적 이유

**실제 봇 답변(발췌):**
> # 서울대의 도심 부동산 미취득 — 이유와 구조적 분석
> 
> ---
> 
> ## 🔑 핵심 결론 먼저
> 
> > **제공된 자료에는 "서울대가 도심 부동산을 구입하지 않는 이유"를 직접 설명한 문서가 없습니다.** 다만 자료 전반의 재정·법인·자산 구조에서 **구조적 제약과 미취득의 합리적 이유**를 유추할 수 있습니다. 동시에 질문하신 대로 **임차 대신 취득이 재정적으로 더 유리할 수 있다는 논리도 성립**합니다.
> 
> ---
> 
> ## 📊 서울대 현재 부동산 자산 구조 — 도심 자산은 보이지 않는다
> 
> 자료에서 확인되는 서울대 보유 부동산은 다음과 같습니다 [중장기발전계획] 중장기-제2장-멀티캠퍼스:
> 
> | 캠퍼스 | 건물(동) | 토지(필지) | 토지면적(㎡) |
> |---|---:|---:|---:|
> | 관악 | 7동 미활용 포함 | 28 | 233,522 |
> | 수원 | 10 | 4 | 56,667 |
> | 연건 
>   […중략…]
>   [중장기발전계획] 중장기-제2장-재정하고 있어, 향후 도심 부동산 취득 전략으로 발전할 가능성이 있습니다.
> 
> ---
> 
> ## ⚠️ 분석의 한계
> 
> **치의학대학원의 혜화 로터리 임차 현황, 임차료 규모, 도심 건물 취득 검토 여부**에 대한 직접 자료가 제공된 위키에 포함되어 있지 않습니다. 위 분석은 재정·법인·자산 구조 자료에서 **구조적으로 유추**한 것으로, 실제 의사결정 배경은 기획처·재정전략실의 내부 검토 자료를 통해 확인이 필요합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [11] 모델: `opinion-grounded`  ·  158자 · tier1 · 위키: senate, board, finance, vision, plan, history, status

**Q:** 지금까지 질문과 답변을 정리하면 서울대 예산은 고정성 예산이 많지만, 총장이 가용 예산을 늘리려면 기부금을 늘리는 수밖에 없고, 2034년 이후 적자 예상하는데 이를 해결하려면 구조적 재정 수입 성장과 학교채 발행을 적극적으로 고민해야 하겠네? 이것 외에 더 생각해볼 것을 정리해줘.

**평가자 aspect 판정:**
  - 서울대 예산의 고정성 및 가용예산 확대 방안(기부금 증대) **[yes]**
  - 2034년 이후 예상되는 적자 현황 **[partial]**
  - 구조적 재정 수입 성장과 학교채 발행을 제외한 추가 대안 **[no]**
  - 예산 심의 프로세스 개선 및 거버넌스 강화 방향 **[yes]**

**부족(missing):** 구조적 재정 수입 성장 외 대체 재원 확보 방안 · 2034년 적자 예상의 구체적 근거 및 규모 · 학교채 발행 제외 시 대안들의 실현 가능성 평가

**실제 봇 답변(발췌):**
> # 서울대 재정 전략 — 논의 확장 정리
> 
> ---
> 
> ## 🔑 질문의 전제 재검토부터
> 
> > 말씀하신 진단은 대체로 정확하지만, **한 가지 중요한 수정**이 필요합니다.
> 
> "기부금을 늘리는 수밖에 없다"는 것은 **과소평가**입니다. 앞선 대화에서 확인했듯 경로는 7개 범주입니다. 다만 **단기 효과 vs. 구조적 해결** 측면에서 우선순위가 다릅니다. 이를 포함해 아직 충분히 다루지 않은 관점들을 아래에 정리합니다.
> 
> ---
> 
> ## 🆕 1. 아직 충분히 논의되지 않은 핵심 관점들
> 
> ### 💸 1-1. 비용 구조 개혁 — "수입 늘리기"만큼 중요한 "지출 효율화"
> 
> 지금까지의 대화는 **수입 확대**에만 집중했습니다. 그러나 2034년 적자의 핵심 원인은 **세출(특히 인건비)의 자동 증가**이므로, 비용 구조 개혁 없이는 수입을 아무리 늘려도 격차가 좁혀지지 않을 수 있습니다.
> 
> | 비용 항목 
>   […중략…]
>   
> | 추가해야 할 관점 ② | **정부와의 협약 재구조화** — 단순 증액 요청이 아닌 계약 관계 수립 |
> | 추가해야 할 관점 ③ | **캠퍼스 자산 수익화** — 관악수목원 등 신규 취득 자산 포함 잠재력 큼 |
> | 추가해야 할 관점 ④ | **등록금 현실화 공론화** — 정치적으로 어렵지만 구조적 해결 없이는 2040 목표 불가 |
> | 추가해야 할 관점 ⑤ | **거버넌스 개혁이 선행** — 재정 전략은 거버넌스 신뢰 없이는 실행 불가 |

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [12] 모델: `opinion-grounded`  ·  108자 · tier1 · 위키: plan, senate, vision, board, history, status, yhl-speeches

**Q:** 새로운 연구 분야, 융합적/학제적 연구 분야의 연구자를 채용하거나 전공/학과를 신설하는 일이 매우 어려워서 사회의 변화를 서울대가 따라가는 데 지장이 많습니다. 이렇게 된 원인을 진단해 주세요.

**평가자 aspect 판정:**
  - 새로운 연구 분야·융합 연구 분야 연구자 채용의 어려움 원인 **[no]**
  - 전공/학과 신설의 어려움 원인 **[no]**
  - 사회 변화 추적 지연의 구조적 원인 진단 **[no]**
  - 현황: 서울대의 융복합연구 지원 체계·성과 **[partial]**

**부족(missing):** 인사·채용 절차상 장애요인 분석 · 학과 신설 규제·행정절차상 장애요인 · 조직 체계의 경직성이 사회변화 대응을 제한하는 이유 · 관련 의사결정 회의 논의 기록·전략문서

**실제 봇 답변(발췌):**
> ## 서울대 신규 연구분야 대응 지체 — 원인 진단
> 
> 제공된 자료를 바탕으로, 이 문제의 원인을 **구조적·제도적·역사적** 세 층위로 진단합니다.
> 
> ---
> 
> ## 🏗️ 1. 학과 칸막이 구조의 역사적 고착
> 
> 서울대는 20세기에 분과 학문별 전문영역에 집중하는 학과체제를 구축하여 선진국과의 학문 격차를 좁히는 데 성공했습니다 [70년역사] 통사-사회경제변화-대학교육. 그러나 이 성공이 오히려 구조적 경직성으로 굳어졌습니다.
> 
> - 2002년 학부제·모집단위 광역화로 칸막이 타파를 시도했으나, **중장기적 전망 결여와 학내 저항**으로 우여곡절 끝에 2016년 현재 "형해화된 상태"라고 70년 역사 자료는 명시적으로 평가합니다 [70년역사] 통사-사회경제변화-대학교육.
> - 융복합 연구·교육의 필요성을 인식하면서도 **"학과체제의 전문성에만 머물지 않는 개방적 여건 조성"이 구현되지 못했다**는 점이
>   […중략…]
>    **재정 제약** | 신규 분야 신설에 필요한 독립적 재원 확보 구조 미비 [중장기발전계획] 중장기-제3장-추진계획 |
> 
> 중장기발전계획이 "학과 간 장벽 없애기"를 7대 핵심과제의 **첫 번째**로 올린 것 [중장기발전계획] 중장기-제1장은, 이 문제가 서울대 스스로도 가장 시급하고 어려운 과제로 인식하고 있음을 보여줍니다. 동시에 그 과제가 수년째 "계획" 단계에 머무르는 이유가 바로 위에서 진단한 구조적 요인들에 있다고 자료는 시사합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [13] 모델: `opinion-grounded`  ·  93자 · tier1 · 위키: senate, board, vision, plan, finance, status, history

**Q:** 서울대학교 본부의 중앙 리더십과 각 교육기구의 독립적이고 주체적인 의사결정 사이의 적절한 균형을 어떻게 찾아야 할지, 서울대학교의 경쟁력과 비전과는 어떤 관련이 되는지

**평가자 aspect 판정:**
  - 서울대 본부 중앙 리더십과 교육기구 간 의사결정 권한 분배의 현황 **[partial]**
  - 본부-단과대/교육기구 간 거버넌스 갈등·긴장 사례 **[yes]**
  - 본부-평의원회 간 권력 균형 및 견제 메커니즘 **[yes]**
  - 이러한 거버넌스 균형이 서울대의 경쟁력·비전과 어떻게 연결되는지에 대한 전략적 진단·제언 **[no]**

**부족(missing):** 중앙 리더십 vs 교육기구의 의사결정 권한 분배 원칙·기준에 관한 공식 정책 기록 · 거버넌스 균형이 경쟁력·비전과 어떻게 기여하는지에 대한 서울대의 전략적 입장·분석

**실제 봇 답변(발췌):**
> # ⚖️ 중앙 리더십 vs. 교육기구 자율성: 서울대학교의 균형 과제
> 
> ---
> 
> ## 1. 문제의 역사적 뿌리 — "연립대학"에서 "종합대학"으로
> 
> 서울대학교의 중앙-자율 긴장은 개교 이래 내재된 구조적 문제입니다.
> 
> > "외형적 틀은 종합대학교였지만 실제로는 각 단과대학들이 기존 전신 학교들의 전통과 관행을 이어받아 거의 독자적으로 운영되었다. 이를 일컬어 **연립대학**이라고 부르기도 했다." [70년역사] 캠퍼스-종합화
> 
> 캠퍼스 종합화(1975년 관악 이전)와 법인화(2011년) [70년역사] 통사-법인화-탄생는 이 긴장을 제도적으로 풀려는 두 번의 대전환이었습니다. 그러나 제도적 통합이 곧 실질적 통합을 의미하지는 않았고, 오늘날까지 **중앙 조정 기능 vs. 학문단위 자율성** 문제는 현재진행형입니다.
> 
> ---
> 
> ## 2. 현재 제도가 드러내는 긴장의 구조
> 
> ### 📌 중장기발전계획이 
>   […중략…]
>    "자발적 참여 유도"로
> 3. 대형 정책은 반드시 구성원 심의(평의원회) 선행
> 4. 평가 기준은 학문단위 특성에 맞게 트랙별 분리
> 5. 비전 공감대 형성은 선언이 아닌 반복적 소통과 참여 구조로
> ```
> 
> ---
> 
> ⚠️ **자료 한계**: 단과대학별 자율성 수준의 실제 운영 현황, 본부-단과대 간 갈등의 구체 사례 등은 제공된 공개 자료 범위 밖에 있습니다. 위 내용은 평의원회·이사회·중장기발전계획·대학운영계획·70년역사 자료를 종합한 것입니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [14] 모델: `opinion-grounded`  ·  80자 · tier1 · 위키: senate, board, plan, vision, history, status, yhl-speeches, finance

**Q:** 서울대학교는 현재의 "종합대학" 체계가 최선의 운영 방식인가? 개별 단과대학의 자율성을 보장하는 방안에 대해서 논의된 주요 역사를 정리해 보자.

**평가자 aspect 판정:**
  - 서울대학교 종합대학 체계의 최적성에 대한 평가 또는 검토 기록 **[no]**
  - 단과대학(학부) 자율성 보장 방안에 대한 논의 또는 제안 **[partial]**
  - 단과대학 자율성 관련 주요 역사적 논의 또는 정책 결정 사례 **[partial]**
  - 대학 거버넌스 구조 개선과 관련된 논의 **[yes]**

**부족(missing):** 종합대학 체계의 '최적성' 평가(질문의 핵심은 가치 판단) · 단과대학 자율성 보장 방안의 구체적·역사적 논의 전개 · 단과대학 자율성과 중앙 본부 통제의 긴장 관계 분석

**실제 봇 답변(발췌):**
> # 서울대학교 "종합대학" 체계와 단과대학 자율성 — 주요 역사적 논의
> 
> ---
> 
> ## 🏛️ 1. 출발점: "연립대학"이라 불렸던 초창기 (1946~)
> 
> 서울대학교는 1946년 개교 당시 경성대학과 여러 관립 전문학교를 하나의 틀에 묶는 종합대학교를 지향했으나, 실제로는 **각 단과대학들이 기존 전통과 관행을 이어받아 거의 독자적으로 운영**되었다 [70년역사] 캠퍼스-종합화. 이러한 실상을 일컬어 당시에는 **"연립대학"**이라고 부르기도 했다 [70년역사] 캠퍼스-종합화.
> 
> 캠퍼스가 여러 군데로 흩어져 있었던 점도 실질적 종합화가 이루어지지 못한 원인이자 결과로 작용했다. 대학본부로부터 사범대학은 2㎞, 공과대학은 18㎞, 농과대학은 45㎞나 떨어져 있어 동일 과목과 시설이 단과대학별로 중복 설치되는 비효율이 발생했다 [70년역사] 캠퍼스-종합화.
> 
> > 즉 "종합대학"이라는 이름이 붙은 순간
>   […중략…]
>   회 견제 | 절차적 정당성 요구 반복 |
> 
> 서울대학교 역사를 통해 볼 때, "종합대학의 최선"이라는 질문은 **종합화의 실질적 달성과 단과대학 자율성의 균형을 어떻게 잡는가**의 문제로 계속 변주되어 왔다. 현재도 중장기발전계획은 "교육단위와 연구단위의 분리 운영" [중장기발전계획] 중장기-제2장-연구, "본부 의사결정 간소화와 단과대학에의 위임" [중장기발전계획] 중장기-제2장-운영체제을 방향으로 제시하고 있어, 이 논쟁은 아직 진행 중이다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [15] 모델: `opinion-grounded`  ·  80자 · tier1 · 위키: finance, vision, board, plan, history, status

**Q:** 2034년부터 세입·세출 격차 발생(60억원) → 2040년 적자 1,098억원 라고 적혀있는데 왜 2034년부터 적자 발생한다고 예측하는거지?

**평가자 aspect 판정:**
  - 2034년부터 세입·세출 격차(60억원) 발생 시점의 정의 **[yes]**
  - 2040년 적자 규모(1,098억원)의 수치 **[yes]**
  - 2034년 격차 발생 → 2040년 적자 확대의 인과 기전·근거(왜 그렇게 악화되는지) **[no]**
  - 적자 예측의 세부 가정·재정 시나리오(수입 정체, 비용 상승 등의 구체적 원인) **[partial]**

**부족(missing):** 2034~2040년 간 세입·세출이 어떻게 악화되는지의 구체적 메커니즘(수입 증가율 둔화, 비용 증가율 가속 등) · 2034년에 정확히 60억원 격차가 발생하는 이유·가정 · 2034년부터 '적자 발생'이라고 표현되는 것이 아니라 '격차 발생'으로 표현된 이유(구분의 의도)

**실제 봇 답변(발췌):**
> # 2034년 적자 전환 예측의 근거 분석
> 
> ---
> 
> ## 🔑 핵심 결론
> 
> > **솔직히 말씀드리면, 제공된 자료에는 "2034년부터 적자가 발생하는 이유"에 대한 구체적인 산출 근거(세입·세출 항목별 증가율 가정, 시나리오 모델링 등)가 포함되어 있지 않습니다.**
> > 다만 자료 전반에서 확인되는 구조적 요인들로부터 **왜 그런 예측이 나올 수밖에 없는지**를 논리적으로 재구성할 수 있습니다.
> 
> ---
> 
> ## 📊 자료에서 확인되는 재정 전망 수치
> 
> | 시점 | 내용 |
> |---|---|
> | 2020년 | 기준 재정 규모 1조 6,000억원 |
> | 2034년 | 세입·세출 격차 **최초 발생 (+60억원 적자)** |
> | 2040년 | 적자 규모 **1,098억원** |
> | 2034~2040년 | 7년간 누적 추가 소요 **4,108억원 → 학교채 발행으로 충당 계획** |
> 
> [중장기발전계획] 
>   […중략…]
>   *의도적 투자 확대**가 전제된 적자입니다
> - 즉 2034년 이후 적자는 **무능에 의한 적자가 아니라 성장 투자에 의한 전략적 적자**로 설계된 측면이 있음
> 
> ---
> 
> ## ⚠️ 분석의 한계
> 
> 제공된 자료에는 **연도별 세입·세출 시뮬레이션 모델, 항목별 증가율 가정치, 2034년 60억원 적자 도출의 구체적 계산식**이 포함되어 있지 않습니다. 정확한 산출 근거를 확인하려면 중장기발전계획 원문의 재정 부속 자료(재정추계 모델)가 필요합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [16] 모델: `opinion-grounded`  ·  78자 · tier1 · 위키: senate, board, plan, vision, status, history

**Q:** 관악수목원을 수목장 묘지로 활용하는 아이디어는 좋아. 다만 요양시설-호스피스병동-장례식장은 관악캠퍼스의 낙성대 인근 부지를 활용하면 어떨까?

**평가자 aspect 판정:**
  - 관악수목원의 수목장 묘지 활용 아이디어 평가 **[partial]**
  - 낙성대 인근 부지의 현황·활용 계획 **[partial]**
  - 요양시설-호스피스병동-장례식장 건립 계획·타당성 **[no]**
  - 관악캠퍼스 낙성대 인근 부지 활용의 적절성·실현 가능성 판단 **[no]**

**부족(missing):** 낙성대 인근 부지의 구체적 용도·활용 계획 현황 · 요양시설·호스피스병동·장례식장 건립 관련 서울대 내부 논의·계획 · 두 부지(관악수목원 vs 낙성대 인근) 비교 검토 기록 · 캠퍼스 마스터플랜에서 낙성대 부지의 위치·규모·제약사항

**실제 봇 답변(발췌):**
> # 관악캠퍼스 낙성대 인근 — 요양·호스피스·장례 복합시설 가능성 분석
> 
> ---
> 
> ## 📍 낙성대 인근 부지의 맥락 — 자료에서 확인되는 신호
> 
> 흥미롭게도 제공된 자료에서 **낙성대 인근이 이미 서울대의 전략적 개발 검토 지점으로 명시**되어 있습니다:
> 
> > **"서울시 추진 중 낙성대 영어마을 일대 'S관악밸리 벤처창업거점공간 조성 기본구상 용역' — 기간 9개월 연장, 2026.6 종료 예정"** [대학운영계획] 2026-운영계획-실행과제7
> > **"서울시·관악구 등과 지속적·긴밀한 협조체계 유지, 타당성 용역 등 후속단계 진입 추진"** [대학운영계획] 2026-운영계획-실행과제7
> 
> 즉 낙성대 인근은 현재 **창업밸리(S관악밸리) 조성 후보지**로 서울시·관악구와 공동 검토 중인 지점입니다. 이는 두 가지 시사점을 줍니다:
> 
> 1. ✅ **해당 부지가 이미 "개발 가능한 부지"로 인식되고 있
>   […중략…]
>    | 🟠 어려움 | 서울대병원 협약 + 의료기관 설치 허가 |
> 
> ---
> 
> ## ⚠️ 분석의 한계
> 
> 낙성대 인근의 **정확한 용도지역, 순환도로 안팎 여부, 창업밸리 용역의 대상 구역 경계**에 대한 직접 자료가 제공된 위키에 없습니다. S관악밸리 기본구상 용역(2026.6 종료 예정) [대학운영계획] 2026-운영계획-실행과제7 결과가 나오면 실제 가용 부지 범위가 명확해질 것이며, 그 이후 요양·장례 복합시설의 구체적 입지 검토가 가능합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [17] 모델: `opinion-grounded`  ·  61자 · tier1 · 위키: board, senate, history, vision, plan, finance, status

**Q:** 서울대의 최근 5년간 재정 구조는 어떻게 변화했으며, 국고지원금·발전기금·산학협력수익의 비중은 어떻게 되나요?

**평가자 aspect 판정:**
  - 최근 5년간(2020~2025) 재정 구조 변화 추이 **[partial]**
  - 국고지원금(정부출연금) 비중 변화 **[partial]**
  - 발전기금 비중 변화 **[no]**
  - 산학협력수익 비중 변화 **[no]**

**부족(missing):** 2020~2022년도 재정 구조 데이터 (2023~2024년 일부만 존재) · 발전기금 수익의 구체적 규모 및 비중 · 산학협력수익의 구체적 규모 및 비중 · 5년간의 비교 분석 (현재는 단년도 또는 2개년도 자료만 제시) · 재정 구조 변화의 원인·배경·의도에 관한 분석

**실제 봇 답변(발췌):**
> # 서울대학교 최근 5년간 재정 구조 변화 분석
> 
> ---
> 
> ## 📊 전체 운영수익 규모 변화 (종합 기준)
> 
> | 연도 | 운영수익 합계 | 전년比 증감 |
> |------|----------:|----------:|
> | 2020 | 15,875억원 | — |
> | 2021 | 17,922억원 | +12.9% |
> | 2022 | 18,363억원 | +2.5% |
> | 2023 | 21,438억원 (추정) | — |
> | 2024 | 21,438억원 | +45.6% (2017 대비) |
> 
> [재무정보공시] 재원구조분석
> 
> 5년간 운영수익은 약 **35% 이상 성장**했으며, 수입원별 구조는 다음과 같이 변화했습니다.
> 
> ---
> 
> ## 💰 3대 핵심 수입원별 비중 변화
> 
> ### 1. 정부출연금 (국고지원금)
> 
> | 연도 | 금액(억원) | 운영수익 비중 |
> |------|----------:|----------:|
>   […중략…]
>   *: 최근 5년간 서울대 재정의 핵심 변화는 ① **산학협력수익의 단일 최대 수입원 부상**, ② **정부출연금의 절대액 증가에도 불구한 비중 안정**, ③ **기부금의 높은 변동성 지속**, ④ **등록금 비중의 지속 하락**으로 요약됩니다. 전반적으로 정부 의존도는 42.4%(2017) → 38.3%(2024)로 점진적으로 낮아지는 추세이며, 민간 재원(산학협력+기부금) 비중이 50% 내외에서 안정되고 있습니다 [재무정보공시] 재원구조분석.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [18] 모델: `opinion-grounded`  ·  58자 · tier1 · 위키: senate, status, board, vision, history

**Q:** 서울대학교에서 신임교원 임용 절차를 단과대학의 특성을 고려하지 않고 일괄적으로 운영하는 이유는 무엇인가?

**평가자 aspect 판정:**
  - 서울대 신임교원 임용 절차의 현재 운영 방식 (일괄 vs 단과대학별 특성 고려) **[partial]**
  - 단과대학의 특성 차이 인식 및 교원 임용 시 반영 필요성 **[partial]**
  - 현재 일괄적 운영을 하게 된 구체적 이유·배경·정책 결정 과정 **[no]**
  - 향후 개선 방향 또는 정책 입장 **[no]**

**부족(missing):** 신임교원 임용 절차가 실제로 '일괄적'으로 운영되고 있는지 여부 확인 불충분 · 단과대학 특성(인문·자연·공학·예술 등)에 따라 임용 절차를 다르게 운영해야 한다는 필요성이 기록에 명시되지 않음 · 일괄 운영 방식의 구체적 결정 이유·정책 논리 부재 · 관련 교원인사위원회·교무처의 공식 입장 또는 회의 기록 부재

**실제 봇 답변(발췌):**
> ## 서울대학교 신임교원 임용 절차의 일괄 운영 여부
> 
> 제공된 자료를 검토한 결과, **"단과대학 특성을 고려하지 않고 일괄적으로 운영한다"는 전제 자체가 자료에서 확인되지 않습니다.** 오히려 자료에는 이와 반대되는 방향의 내용이 포함되어 있습니다.
> 
> ---
> 
> ### 📋 자료에서 확인되는 실제 내용
> 
> **1. 심사위원 규정의 단과대 적용 한계 문제**
> 
> 평의원회에서는 교원 인사규정 시행세칙 개정 심의 시, "심사위원 규정이 교원 수가 적은 단과대학에는 적용하기 어렵다"는 어려움이 지적되었습니다 [평의원회] 18기-13차. 이는 일률적 규정 적용이 오히려 **소규모 단과대학에 현실적 부담**이 된다는 문제를 내부에서 인식하고 있음을 보여줍니다.
> 
> **2. 수정 심의 결과 — 단서조항 유지**
> 
> 위 지적에 따라 해당 세칙은 원안이 아닌 **수정 심의**로 처리되었으며, 단서조항을 유지하는 방향으로
>   […중략…]
>   는 계획이 별도로 발표되었습니다 [평의원회] 17기-23차. 이는 새로운 형태의 교육기구에 대해서는 별도의 채용 방식이 적용됨을 보여줍니다.
> 
> ---
> 
> ### ⚠️ 답변의 한계
> 
> 질문의 전제인 "일괄 운영의 이유"에 대한 공식적 설명이나 정책 근거는 제공된 자료 범위 내에 존재하지 않습니다. 임용 절차의 구체적 운영 방식 및 그 설계 배경에 대한 상세 자료는 현재 제공된 위키 범위 밖에 있으며, 이를 추측하여 답변드리는 것은 적절하지 않습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [19] 모델: `opinion-grounded`  ·  58자 · tier1 · 위키: senate, board, finance, plan, vision, history, status, yhl-speeches

**Q:** 서울대 교육관련해서 주요 포인트의 변천사를 먼저 개괄적으로 알려주면, 세부 사항에 대해 질문하려고 한다.

**평가자 aspect 판정:**
  - 서울대 교육 관련 주요 정책·제도의 역사적 변천 **[partial]**
  - 교육 개혁·혁신의 시간 순서와 구체적 내용(학제, 교과과정, 조직 등) **[partial]**
  - 교육 정책 변화의 배경·동인·영향 **[no]**
  - 전체 개괄적 흐름(timeline/로드맵) 제시 **[no]**

**부족(missing):** 교육정책 변천의 연대기적 정리 및 개괄 서술 · 각 정책의 추진 배경·동인·영향·성과에 대한 분석 · 핵심 교육 이슈별 진화 과정의 종합 설명 · 전체 시간대를 아우르는 교육 발전 전략의 변화 추이

**실제 봇 답변(발췌):**
> # 서울대학교 교육 관련 주요 포인트 변천사 개괄
> 
> 아래는 70년 역사·중장기발전계획·대학운영계획·총장연설 등 위키 자료를 교차 종합한 흐름입니다.
> 
> ---
> 
> ## 📚 시대별 교육 핵심 포인트 요약 테이블
> 
> | 시기 | 핵심 키워드 | 주요 내용 | 출처 |
> |---|---|---|---|
> | 1946~1960년대 | **연립대학 → 종합화 모색** | 개교 당시 각 단과대학이 독립 운영("연립대학"). 1958년 종합계획수립위원회 구성, 종합화 10개년 계획 수립(1968) | [70년역사] 캠퍼스-종합화 |
> | 1970년대 | **대학원중심대학 1기** | 연구·교육 중심을 학부→대학원으로 이동 첫 시도. 정부 정책 일관성 부재로 지속 실패 | [70년역사] 연구중심대학-후-교육운영-변화 |
> | 1975년 | **관악캠퍼스 종합화 완성** | 분산 캠퍼스 통합, 실질적 종합대학 구현 | [7
>   […중략…]
>   19차, 19기-3차
> - **총장 의제 설정의 연속성**: 유홍림 총장은 취임(2023)~80주년(2026)까지 "대전환·융합·칸막이 철폐"를 일관된 프레임으로 유지 [유홍림총장연설] 취임사-2023, 대전환의시대.유홍림.stance
> 
> ---
> 
> 특정 시기(예: 1990년대 연구중심대학 전환기), 특정 제도(예: 학부대학·첨단융합학부의 도입 과정), 또는 거버넌스 쟁점(예: 평의원회의 교육 안건 심의 패턴) 중 어느 부분을 더 자세히 살펴볼까요?

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [20] 모델: `opinion-grounded`  ·  57자 · tier1 · 위키: senate, board, finance, vision, plan, status

**Q:** 새로운 임기를 시작하는 총장이 서울대 발전을 위한 전략적인 기획을 하려 한다면 가용한 예산은 얼마일까?

**평가자 aspect 판정:**
  - 총장의 전략적 기획에 필요한 예산 규모 **[partial]**
  - 예산 편성 프로세스 및 의사결정 구조 **[yes]**
  - 구체적인 가용 예산액(연간/다년간) **[no]**
  - 예산 배분 기준 및 우선순위 **[partial]**

**부족(missing):** 구체적인 연간 법인회계 예산액(세입·세출 총규모) · 대학운영 자유재량 예산(전략적 투자 가능 규모) · 중기 재정계획(복수년도 예산 추이) · 외부 기금·기부금·정부출연금 확보 현황

**실제 봇 답변(발췌):**
> # 신임 총장의 전략적 가용 예산 추산
> ## — 2026년도 기준 실질 집행 가능 재원 종합 분석
> 
> ---
> 
> ## 🔑 핵심 결론 (먼저 요약)
> 
> > **명목 예산 1조 2,038억원 중, 신임 총장이 새로운 전략에 실질적으로 투입 가능한 예산은 약 1,500~1,800억원 수준으로 추산됩니다.**
> > 단, 이 범위 내에서도 기존 공약·협약·예산 편성 사이클의 제약이 존재합니다.
> 
> ---
> 
> ## 📊 1. 전체 예산 구조와 전략 가용성 분류
> 
> | 분류 | 금액(억원) | 비중 | 전략 가용성 |
> |---|---:|---:|---|
> | 🔒 인건비 | 4,860 | 40.4% | 없음 — 법령·계약 의무 |
> | 🔒 책임운영경비(수입대체) | 1,237 | 10.3% | 없음 — 수익 연동 |
> | 🔒 준고정성 운영비 | 1,620 | 13.5% | 거의 없음 — 기본 운영 유지 |
> | △ 적립금·예비비 
>   […중략…]
>   규 구분 명세**가 제공 자료에 없어 고착 비중(~2,500억)은 추산입니다. 예산 세부사업 명세서 확인 시 정밀화 가능합니다.
> 2. **취임 시점**에 따라 가용 범위가 크게 달라집니다 — 예산 편성 전(8~10월) 취임 vs. 편성 후(2~3월) 취임은 차이가 큽니다.
> 3. 산학협력단(별도 법인, 2024년 결산 세입 약 1조 1,146억 중 산학 포함)은 연구과제 기반 자금으로 총장의 직접 배분 권한이 제한됩니다 [이사회] 2024-3차.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [21] 모델: `opinion-grounded`  ·  55자 · tier1 · 위키: senate, plan, board, yhl-speeches, vision, status

**Q:** 나눔기반 인재육성과 “ AI 기반 협력성과 아카이브 플랫폼 구축, 시범국가 성과측정”이 무슨 상관?

**평가자 aspect 판정:**
  - 나눔기반 인재육성의 정의 및 의미 **[yes]**
  - AI 기반 협력성과 아카이브 플랫폼 구축의 내용 **[yes]**
  - 시범국가 성과측정의 구체적 내용 및 방식 **[yes]**
  - 두 사업 간의 직접적 연관성·논리적 연결고리 **[partial]**

**부족(missing):** 두 사업이 어떤 논리로 연결되는지에 대한 명시적 설명 (문서는 '나눔기반 인재육성' 섹션에서 두 사업을 병렬로 나열하나, 왜 이들이 상관관계 있는지 구체적으로 설명하지 않음)

**실제 봇 답변(발췌):**
> # 나눔기반 인재육성과 "AI 기반 협력성과 아카이브 플랫폼"의 연관성
> 
> 좋은 질문입니다. 언뜻 보면 **'나눔'과 'AI 플랫폼'이 어색하게 결합**된 것처럼 보이는데, 자료를 통해 그 맥락을 재구성하면 다음과 같습니다.
> 
> ---
> 
> ## 🔍 핵심 구조: 무엇을 위한 플랫폼인가?
> 
> 실행과제 5의 세부 내용을 보면, AI 기반 플랫폼은 **글로벌 사회공헌단 해외봉사 프로그램의 성과관리 도구**로 설계되어 있습니다.
> 
> > "2026년 시범국가 대상 AI 기반 활동데이터 수집·공동평가 플랫폼 베타테스트 준비, 현지 주체의 참여적 평가(Participatory Evaluation) 방식 시범 도입, 글로벌 해외봉사의 **정성적 개발효과 측정 지표** 단계적 개발 추진"
> > [대학운영계획] 2026-운영계획-실행과제5
> 
> 즉, AI 플랫폼의 목적은 **봉사·나눔 활동의 실질적 효과를 측정·기록하는 인프라 
>   […중략…]
>   및 확대 기반 마련
> ```
> 
> ---
> 
> ## ⚠️ 다만, 한계도 있습니다
> 
> 자료 어디에도 **'나눔기반 인재육성'의 공식 정의**나 **AI 플랫폼과 인재 역량 간의 인과관계에 대한 이론적 근거**는 명시되어 있지 않습니다. 왜 AI 플랫폼 구축이 **인재育성**의 과제로 분류되는지에 대한 설명은 운영계획 내에서 **암묵적으로 전제**될 뿐, 명시적으로 서술되지는 않습니다. 이 점에서 과제 구성의 논리적 연결이 다소 느슨하다는 지적도 가능합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [22] 모델: `opinion-grounded`  ·  53자 · tier1 · 위키: senate, board, finance, vision, plan, history, status

**Q:** 이 대화창에서는 서울대 거버넌스를 다룰거야. 서울대 거커넌스의 문제를 중요도 순서대로 정리해줘.

**평가자 aspect 판정:**
  - 서울대 거버넌스의 주요 문제점/쟁점 식별 **[partial]**
  - 식별된 문제들의 중요도 순위 결정 기준 **[no]**
  - 문제들을 중요도 순서대로 정렬한 리스트 **[no]**

**부족(missing):** 거버넌스 문제의 중요도를 판정하는 기준(예: 영향 범위, 시급성, 구성원 영향도) · 평의원회 자신이 공식 선정한 우선순위 문서 · 문제의 상대적 중요성을 판단할 수 있는 메타 정보

**실제 봇 답변(발췌):**
> # 서울대학교 거버넌스의 주요 문제 (중요도 순)
> 
> 제공된 위키 자료에서 확인되는 거버넌스 문제들을 중요도 순으로 정리합니다.
> 
> ---
> 
> ## ⚖️ 1. 이사회-평의원회 간 권한 경계 불명확
> 
> 서울대 정관은 이사회를 "최고 의사결정기구"로 규정하고 있으나 [대학현황] 조직도-개요.fact, 실제 운영에서는 평의원회가 독자적 심의권을 행사하며 본부 안건을 반복 거부하는 사례가 발생했습니다.
> 
> - **본부 발의 안건 부결 사례 2건** [평의원회]:
>   - 선도연구진흥센터 설립 **표결 부결** (찬13/반16/기1) [평의원회] 17기-12차
>   - 교육위원회 자문기구화 시도 → **현행 유지로 결정** [평의원회] 18기-14차
> - **정관 개정안 압도적 부결**: 이사회 제출 정관 개정안이 평의원회에서 **찬1/반32**로 부결 [평의원회] 18기-5차
> - 2025년 이사회는 "**평의원회 의
>   […중략…]
>   대학 추진단 무단 구성 사례 |
> | 5 | 이사회 내부 대표성 부족 | 법인화 이래 반복된 외부자 지배 구조 |
> | 6 | 심의기구 과다·중복 | 정관+학칙 기준 25개 이상 심의·자문기구 |
> 
> ---
> 
> > **자료 범위 한계**: 제공된 자료는 평의원회 17~19기(2021~2025), 이사회 2023~2026년 의사록 중심입니다. 총장선출 제도 개선 정책연구의 최종 결과(19기-4차)는 현재 제공된 자료 범위 밖에 있어 포함하지 않았습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [23] 모델: `opinion-grounded`  ·  51자 · tier1 · 위키: senate, vision, history, status, yhl-speeches

**Q:** 외부에서 서울대학교를 보는 시선, 최근의 사회적 이슈에서 서울대학교가 부정적으로 언급된 사례

**평가자 aspect 판정:**
  - 외부에서 서울대학교를 보는 시선(외부 평판, 사회적 인식) **[no]**
  - 최근 사회적 이슈에서 서울대학교가 부정적으로 언급된 사례 **[partial]**

**부족(missing):** 외부 평판·외부 인식·언론 평가에 관한 정보 · 부정적 사회적 이슈 사례(구체적 사건, 언론 보도, 사회 반응 등)

**실제 봇 답변(발췌):**
> # 외부 시선과 사회적 이슈에서 서울대학교의 부정적 언급 사례
> 
> ---
> 
> 제공된 자료는 주로 서울대학교 내부 문서(평의원회 회의록, 중장기발전계획, 총장 연설 등)로 구성되어 있어, **외부 언론·사회의 시선을 체계적으로 정리한 자료는 포함되어 있지 않습니다.**
> 
> 다만, 제공된 자료 안에서 **외부로부터의 비판적 시선이 간접적으로 반영된 사례**는 다음과 같이 확인됩니다.
> 
> ---
> 
> ## 📌 자료 내에서 확인되는 외부 비판 관련 단편
> 
> ### 1. 의대 증원 사태 — 교육부 감사 대상 통보
> - 2024년 의대 증원 사태와 관련해 **교육부가 서울대를 감사 대상 기관으로 통보**하는 절차 문제가 평의원회에서 지적됨. 평의원회는 "대학의 자율성 보장을 위한 본부 노력"을 당부 [18기-11차]
> 
> ### 2. 재정 공시 관련 국회·정부의 오해 가능성
> - 종합재무제표의 **정부출연금·보조금 비중 표시
>   […중략…]
>   장은 개교기념사에서 "우리는 얼마나 절박합니까?"라며 서울대 스스로의 혁신 부재를 공개적으로 문제 제기 [개교기념사-77주년-2023]
> 
> ---
> 
> ## ⚠️ 자료 범위의 한계
> 
> 외부 언론 보도, 사회적 여론, 국정감사 발언 등 **서울대를 향한 외부 비판을 직접 수록한 자료는 현재 제공된 위키 범위에 포함되어 있지 않습니다.** 관련 내용을 원하신다면 언론 자료나 국정감사 기록 등 별도 자료를 추가로 제공해 주시면 더 정확한 답변이 가능합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [24] 모델: `opinion-grounded`  ·  50자 · tier1 · 위키: status, senate, board, plan, history

**Q:** 전문 관리자(테크니션, 장비운영인력) 고용에 대한 구체적인 수요 제기 또는 논의가 있었나?

**평가자 aspect 판정:**
  - 전문 관리자(테크니션, 장비운영인력) 고용의 구체적 수요 제기 여부 **[partial]**
  - 해당 수요에 대한 논의·검토 결과 **[partial]**
  - 고용 확대 또는 인력 확보 관련 구체적 대책·계획 **[no]**

**부족(missing):** 테크니션·장비운영인력 등 전문 관리자 고용에 대한 구체적 수요 규모·사항 · 논의 후 채택된 실행 계획 또는 인력 확보 방안의 구체적 내용 · 재정 배분 또는 조직 개편을 통한 대응 방안

**실제 봇 답변(발췌):**
> ## 🔬 고가 장비 전문 관리자 고용 관련 논의
> 
> 제공된 위키 자료에서 **장비 전문 관리자(테크니션) 고용**을 직접적으로 다룬 안건은 없습니다. 다만, 인력 채용·전문 인력 필요성과 관련하여 **참고할 수 있는 유사 논의**가 일부 확인됩니다.
> 
> ---
> 
> ## 👥 관련 인력·전문직 채용 관련 논의 사례
> 
> ### 1. 도서관 사서 → 전산직·행정직 전환 필요성 제기
> 
> > 사서 업무 변화에 따라 **전산직·일반행정직 필요성이 증가**하고 있어 본부 입장을 질의함. 기획처는 "검토 중이며, 연구 과제로 해결 방안을 모색할 예정"이라고 답변함 [평의원회] 18기-10차.
> 
> 이는 직렬 전환·신규 직군 필요성이 제기된 사례로, 장비 전문 인력 채용 논의와 구조적으로 유사합니다.
> 
> ### 2. 창업지원단 전문 인력(변리사) 채용 계획
> 
> > 창업지원 전담조직 설립 논의에서 **산학협력단 직원 파견 + 변리
>   […중략…]
>   렬을 **'공업시설' 직류에 포함 후 삭제**하는 방식으로 처리되었다고 설명됨 [평의원회] 18기-8차.
> 
> 연구장비 관련 직렬이 별도로 존재했음을 시사하는 내용입니다.
> 
> ---
> 
> ## ⚠️ 한계 안내
> 
> 제공된 자료 범위 내에서는 고가 장비 전문 관리자 **채용 절차, 공고 방법, 예산 확보 경로** 등에 대한 구체적인 논의는 확인되지 않습니다. 실질적인 채용 방법은 **연구처(연구지원과)** 또는 **공동기기원**에 직접 문의하시길 권장합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [25] 모델: `opinion-grounded`  ·  50자 · tier1 · 위키: finance, board, senate, history, vision, plan, status

**Q:** 법인화 이후 서울대 재정 구조가 어떻게 변했나? 등록금 동결 기간 재원 구성 변화를 알려줘

**평가자 aspect 판정:**
  - 법인화 이후(2011년~) 재정 구조 전반적 변화 **[partial]**
  - 등록금 동결 기간 명시 및 그 시기 **[no]**
  - 등록금 동결 기간의 재원 구성(수입원 비중) 변화 **[partial]**
  - 동결 기간 정부출연금·기부금 등 대체 재원의 증감 추이 **[partial]**

**부족(missing):** 등록금 동결 구체적 시기·기간 명시 (컨텍스트에는 '동결', '수업료 동결' 언급만 있고 시작·종료 연도 불명확) · 동결 기간에 대한 재정 영향도 분석 (동결이 재원 구조 변화에 미친 인과적 영향 판단 요구)

**실제 봇 답변(발췌):**
> # 법인화 이후 서울대 재정 구조 변화 및 등록금 동결 기간 재원 구성 변화
> 
> ---
> 
> ## 📊 핵심 요약 테이블 (2017→2024, 종합 기준)
> 
> | 항목 | 2017 | 2024 | 변화 |
> |---|---|---|---|
> | 종합 운영수익 합계 | 14,726억원 | 21,438억원 | **+45.6%** |
> | 법인 등록금수입 | 1,873억원 | 1,974억원 | **+5.4%** (거의 동결) |
> | 법인 정부출연금·보조금 | 4,366억원 | 6,229억원 | **+42.7%** |
> | 산학협력단 운영수익 | 6,189억원 | 10,064억원 | **+62.6%** |
> | 종합 당기운영차익 | 349억원 | 1,255억원 | **+259.6%** |
> | 종합 총자산 | 44,923억원 | 70,872억원 | **+57.8%** |
> 
> > 교차 확인: [재무정보공시] 주체별-운영수익.
>   […중략…]
>   화, 사업성과 기반 예산 배분, OCIO 기금 운용(2025년 수익률 9.5%), SNU 홀딩스 기술지주회사 지분인수** 등을 핵심 과제로 설정했습니다 [대학운영계획] 2026-운영계획-실행과제12.
> 
> ---
> 
> **📌 한계 안내**: 법인화 초기(2011~2016년) 데이터는 제공된 자료에 포함되지 않아, 이 분석은 2017~2024년(8개년) 기준입니다. 등록금 동결의 정확한 법적·정책적 경위도 별도 자료가 없어 재무 수치로만 확인하였습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [26] 모델: `opinion-grounded`  ·  48자 · tier1 · 위키: status, senate, plan, vision, history

**Q:** 서울대학교에서 고가 장비/기기를 운영하는 기관에 전문 관리자를 고용할 수 있는 방법은?

**평가자 aspect 판정:**
  - 고가 장비/기기 운영 기관의 정의 및 범위 **[partial]**
  - 전문 관리자 고용 제도 또는 규정의 존재 여부 **[no]**
  - 전문 관리자 고용 절차·기준·재원 **[no]**
  - 관련 부서·위원회·정책 **[partial]**

**부족(missing):** 전문 관리자 고용 제도/규정 · 고가 장비/기기 운영 기관의 인력 운영 정책 · 전문 관리자 고용 절차 및 재원 마련 방안 · 관련 규정 및 예시

**실제 봇 답변(발췌):**
> 제공된 위키 자료에서는 고가 장비/기기 전문 관리자 **고용 방법**에 대한 구체적인 절차나 규정은 포함되어 있지 않습니다.
> 
> 다만, 관련 맥락으로 참고할 수 있는 내용은 다음과 같습니다.
> 
> ---
> 
> ## 🔬 고가 연구장비 공동활용 및 인프라 운영 방향 (2026년 기준)
> 
> **공동기기원 중심의 공동활용 체계**가 운영되고 있으며, 2026년 대학운영계획에서는 다음과 같은 방향이 제시되어 있습니다 [대학운영계획] 2026-운영계획-실행과제9:
> 
> - **초고가 장비(10억원 이상)** 및 **고가 장비(3~10억원)** 구입 지원 및 노후·유휴 장비 수리
> - 공동기기원 중심의 **공동활용 촉진**
> - 장비 선정 시 **기관 대응투자 의무화 도입 예정** (예산 효율성 제고)
> - 안전하고 쾌적한 실험실 환경 구축
> 
> ---
> 
> ## ⚠️ 한계 안내
> 
> 전문 관리자(테크니션, 장비운영인력 등)의 **채용 절차, 직급 체계, 공고 방법** 등 인사·채용 관련 세부 정보는 제공된 자료 범위 내에 포함되어 있지 않습니다.
> 
> 실질적인 고용 방법에 대해서는 **공동기기원** 또는 **연구처(연구지원과)** 에 직접 문의하시는 것이 가장 정확합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [27] 모델: `opinion-grounded`  ·  45자 · tier1 · 위키: senate, board, plan, vision, finance, status, yhl-speeches

**Q:** 지금까지 서울대학교 역대 총장의 전공/전문성과 역점 추진 사업에 연관성이 있는가?

**평가자 aspect 판정:**
  - 서울대학교 역대 총장의 명단·전공·학력·연구 분야 **[no]**
  - 각 총장의 재임 기간 중 추진한 주요 정책·사업·역점 과제 **[partial]**
  - 총장의 학문 전공/전문성과 그 총장이 추진한 사업 간의 인과적 연관성·상관관계 **[no]**
  - 역사적 패턴 분석: 총장 전공과 학교 정책 방향의 일관성 또는 영향도 **[no]**

**부족(missing):** 서울대학교 역대 총장의 명단, 전공 분야, 전문성 · 각 총장의 재임 기간 및 임기 · 총장 개인의 학문적 배경과 학교 정책의 연결 관계 · 역대 총장들의 전공·전문성과 역점 사업 간 상관관계 분석

**실제 봇 답변(발췌):**
> # 서울대학교 역대 총장 전공·전문성과 역점 사업의 연관성
> 
> ## ⚠️ 자료 범위 안내
> 
> 제공된 위키 자료는 **유홍림 총장(제28대, 2023~)** 의 연설과 재임 중 사업에 관한 내용을 주로 다루고 있습니다. **역대 총장들의 전공·전문성 및 재임 중 역점 사업에 대한 체계적 데이터는 제공된 자료 범위에 포함되어 있지 않습니다.**
> 
> ---
> 
> ## 📋 확인 가능한 범위: 유홍림 총장 사례
> 
> 제공된 자료에서 확인할 수 있는 것은 유홍림 총장 1인의 사례입니다.
> 
> | 항목 | 내용 | 출처 |
> |---|---|---|
> | 취임 시기 | 2023년 2월 8일 제28대 총장 | [유홍림총장연설] 취임사-2023 |
> | 주요 역점 사업 | 초학제적 융합교육, SNU 그랜드퀘스트, AI 네이티브 캠퍼스, 학부대학 출범 | [유홍림총장연설] 신년사-2025 [유홍림총장연설 그랜드퀘스트 — 유홍림의 입장
>   […중략…]
>   장의 전공·전문성과 역점 사업 간의 연관성"** 이라는 질문에 체계적으로 답변하기 어렵습니다.
> 
> 이 질문에 답하려면 역대 총장(예: 조순, 이현재, 이수성, 정운찬, 이장무, 오연천, 성낙인, 오세정 등)의 전공 정보와 각 재임 기간의 주요 사업 기록이 필요하며, 해당 내용은 **서울대학교 70년 역사 자료** 또는 별도의 총장 이력 데이터를 통해 확인하시길 권장합니다.
> 
> 특정 총장이나 특정 시기에 대해 더 구체적으로 알고 싶으시면 알려주세요.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [28] 모델: `opinion-grounded`  ·  43자 · tier1 · 위키: senate, board, vision, finance, plan, status

**Q:** 서울대 펀드 레이징을 강화하기 위헤 역대 총장 후보들이 내세운 공약들을 알려줘

**평가자 aspect 판정:**
  - 역대 총장 후보자들(또는 당선인들)이 펀드 레이징 강화를 위해 내세운 구체적 공약·정책 제안 **[no]**
  - 펀드 레이징(기금 모금) 강화 관련 서울대 정책·전략·계획의 기록 **[partial]**
  - 총장 선출 과정에서 공약으로 제시된 발전 전략 일반 **[no]**

**부족(missing):** 역대 총장 후보자들의 구체적 펀드 레이징 공약 · 총장 후보자 공약 관련 기록 · 펀드 레이징 강화 전략의 총장 공약 내용

**실제 봇 답변(발췌):**
> ## 서울대 펀드레이징 관련 총장 후보 공약
> 
> 제공된 위키 자료에는 **역대 총장 후보들이 펀드레이징(기금 모금) 강화를 공약으로 내세운 내용**이 포함되어 있지 않습니다.
> 
> ---
> 
> ### 📌 확인 가능한 관련 내용
> 
> 제공된 자료에서 총장 선출 절차와 관련해 확인되는 내용은 다음과 같습니다:
> 
> - **총장추천위원회 규정 개정** (2023년): 총장 연임이 실질적으로 가능하도록 규정 정비 [이사회] 2023-1차
> - **총장 선출 제도 개선 정책연구** 진행 중 (연구기간 2025-09-21까지 연장) [평의원회] 18기-19차
> - **제29대 총장 선출 절차** 안내 (거버넌스·재정소위원회에서 총장추천위 위원 후보 9명 추천 결정) [이사회] 2026-2차
> 
> 다만 이들 자료에는 개별 후보들의 공약 내용이 포함되어 있지 않습니다.
> 
> ---
> 
> ### 💰 펀드레이징 현황 (참고)
> 
> 총장 공약과는 
>   […중략…]
>   , 2025년 연 수익률 **9.5%** (누적 55.5%) [대학운영계획] 2026-운영계획-실행과제12
> - '만만한기부', '천원의 식샤', '샤인기부' 등 모금 프로그램 운영 [대학운영계획] 2026-운영계획-실행과제12
> 
> ---
> 
> 총장 후보 공약에 관한 자료는 현재 제공된 위키 범위 밖에 있어 답변이 어렵습니다. 혹시 **현재 서울대 펀드레이징 전략이나 재정 확충 방향**에 대해 더 구체적으로 알고 싶으시다면 해당 주제로 질문해 주세요.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [29] 모델: `opinion-grounded`  ·  43자 · tier1 · 위키: senate, board, finance, vision, plan, history, status

**Q:** 서울대 교수들 정년보장 심사 기준을 더욱 엄격하게 해야 한다는 논의가 있었나?

**평가자 aspect 판정:**
  - 서울대 교수 정년보장 심사 기준 관련 논의 존재 여부 **[no]**
  - 정년보장 심사 기준을 더 엄격하게 해야 한다는 주장/제안 존재 여부 **[no]**
  - 정년보장 심사 절차 또는 기준에 대한 평의원회 논의 기록 **[partial]**

**부족(missing):** 정년보장 심사 기준 관련 논의 · 기준 강화/엄격화에 대한 주장 · 정년보장 심사의 구체적 내용

**실제 봇 답변(발췌):**
> ## 서울대학교 교수 정년보장 심사 기준 강화 논의
> 
> 제공된 자료에서 정년보장 심사 기준을 **"더욱 엄격하게 해야 한다"**는 방향의 직접적인 논의는 확인되지 않습니다. 다만, 정년보장 심사 관련 **제도 정비** 논의는 다음과 같이 확인됩니다.
> 
> ---
> 
> ### ⚖️ 「정년보장교원 임용심사위원회 규정」 전부개정 (2024년)
> 
> - 2024년 12월 평의원회 18기 13차 본회의에서 **「정년보장교원 임용심사위원회 규정」 전부개정안**이 심의되어 **원안 심의**로 처리되었습니다 [평의원회] 18기-13차.
> - 다만, 회의 자료에는 이 안건에 대한 쟁점 토론이나 기준 강화 관련 세부 논의 내용이 기록되어 있지 않습니다.
> 
> ---
> 
> ### 🔬 교원 업적평가 제도 개편 (2022년, 간접 관련)
> 
> - 2022년 9월 평의원회 17기 10차 본회의에서 **「교원 인사 규정」 일부개정**이 심의되었는
>   […중략…]
>   - 이는 심사 기준 강화라기보다 **법령 형식 정비**에 가까운 수정이었습니다.
> 
> ---
> 
> ### 📋 한계
> 
> 제공된 자료의 범위 내에서는 정년보장 심사 기준을 **강화해야 한다**거나 **현행 기준이 느슨하다**는 취지의 논의, 또는 외부 심사위원 비율 확대·심사 지표 개선 등 구체적인 기준 강화 방향의 논의는 확인되지 않습니다. 「정년보장교원 임용심사위원회 규정」 전부개정의 구체적 개정 내용 역시 자료에 포함되어 있지 않아 확인이 어렵습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [30] 모델: `opinion-grounded`  ·  43자 · tier1 · 위키: senate, board, vision, history, status

**Q:** 현재 대학의 능동적이고 체계적인 마스터 플랜 수립을 위한 논의가 진행 중인가?

**평가자 aspect 판정:**
  - 현재 대학의 마스터 플랜(master plan) 수립 여부 **[partial]**
  - 마스터 플랜 수립을 위한 논의·회의가 진행 중인지 여부 **[yes]**
  - 마스터 플랜 수립 과정이 능동적이고 체계적인지 여부(평가·진단) **[partial]**

**부족(missing):** 마스터 플랜 수립의 전체 현황·진척도에 대한 종합 평가 · 능동성·체계성에 대한 본부의 자체 평가 또는 공식 입장

**실제 봇 답변(발췌):**
> ## 🏗️ 시흥캠퍼스 마스터플랜 수립 논의 현황
> 
> 제공된 자료 범위 내에서 확인할 수 있는 내용은 다음과 같습니다.
> 
> ---
> 
> ### 1. 관악캠퍼스 마스터플랜: 수립 완료 (2022년)
> 
> 2021년 12월 평의원회에 「2022~2026 서울대학교 캠퍼스 마스터플랜」 수립 계획이 보고·접수되었습니다 [평의원회] 17기-3차. 당시 평의원들은 인간중심·자연친화적 캠퍼스, 연건캠퍼스 교통환경, 장기적 모빌리티 변화 등을 주문하였고, 이 마스터플랜은 **관악캠퍼스 중심**으로 수립된 것으로 보입니다.
> 
> 또한 같은 시기(2022년 2월) 평의원회 정책연구과제로 **「서울대학교 관악캠퍼스 교통체계 마스터플랜 수립」**이 별도로 선정되기도 했습니다 [평의원회] 17기-4차. 이 역시 관악캠퍼스에 국한된 것입니다.
> 
> ---
> 
> ### 2. 시흥캠퍼스 마스터플랜: 사업 후행(後行) 상태
> 
> 앞선 논의에서 확인된 
>   […중략…]
>   |
> 
> ---
> 
> ### ⚠️ 자료 범위 한계
> 
> 제공된 자료는 2025년 7차 이사회 및 18기-19차(2025년 8월) 평의원회까지 포함되어 있으나, **시흥캠퍼스 마스터플랜을 본격적으로 수립하기 위한 별도 위원회 구성, 연구 용역 발주, 공청회 개최 등의 능동적 추진 절차가 진행 중이라는 기록은 확인되지 않습니다.** 마스터플랜의 필요성은 여러 회의에서 언급되었으나, 그것이 구체적 추진 계획으로 전환되었다는 근거는 현재 제공된 자료에 없습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [31] 모델: `opinion-grounded`  ·  43자 · tier1 · 위키: senate, vision, board, finance, status, plan, history

**Q:** 서울대 2040 비전 내용 중 2025년 서울대 주요 시행과제로 실행된 것은?

**평가자 aspect 판정:**
  - 서울대 2040 비전의 구체적 내용 **[partial]**
  - 2025년 주요 시행과제로 실행된 사업(들) **[partial]**
  - 2040 비전과 2025년 실행과제 간의 직접 연결고리 **[no]**
  - 2025년 실행 사업의 구체적 성과/진행 현황 **[partial]**

**부족(missing):** 2040 비전의 상세 목표·전략 내용 · 2040 비전에서 2025년 시행과제로 명시적 도출된 항목 목록 · 2025년 시행과제와 2040 비전 간의 직접 매핑/연계 설명 · 각 2025년 실행 과제의 구체적 성과 평가

**실제 봇 답변(발췌):**
> # 서울대 2040 비전 → 2025년 실행 현황 분석
> 
> ## 개요
> 
> 서울대 중장기발전계획(2022.8. 발간)에서 제시한 **비전 "국가와 인류의 미래에 공헌하는 지식공동체"** 및 **7대 중점 추진과제**가 2025년도 실행과제로 어떻게 구현되었는지를 아래와 같이 정리합니다.
> 
> ---
> 
> ## 🎓 과제 1: 전공·학과 간 장벽 없애기 → **초학제적 융합교육 체제 구축**
> 
> 중장기 계획에서 제안된 입학 모집단위 광역화, 학제적 교육과정 개발, School of Computing 신설 등은 [중장기-제1장] 2025년에 다음과 같이 실행되었습니다.
> 
> - **첨단융합학부 본격 운영**: 학부생 주전공 배정에 따른 첨단분야 전공교육 본격화, 신규 교과목 개발·운영. 5개 전공별 첨단기자재 18종 도입, AI 학습용 서버 설치 [2026-섹션3-추진성과및기본방향]
> - **학부대학 설립·운영 (202
>   […중략…]
>    1인당 연 3,000~4,000만원 최대 4년 지원 [2026-섹션3-추진성과및기본방향]
> - **SKERIC(한-스웨덴 혁신교육연구단)**: 8개 대학 신진연구자 다학제 공동연구, SKERIC Week 2025 개최 [2026-섹션3-추진성과및기본방향]
> 
> ---
> 
> ## 🏛️ 과제 6: 포용적 무장벽 캠퍼스 → **LnL 및 학생복지**
> 
> 중장기 계획에서 "구성원의 총체적 웰니스 증진, 통합적 학생지원" 방향을 제시한 것 [중장기-제2장-학생지

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [32] 모델: `opinion-grounded`  ·  42자 · tier1 · 위키: senate, board, finance, plan, vision, status

**Q:** 서울대 단과대별로 진행하고 있는 주요 사업과, 단과대별 교원 구성을 알려줘.

**평가자 aspect 판정:**
  - 서울대 단과대별 주요 사업 현황 **[partial]**
  - 서울대 단과대별 교원 구성(정원, 직급 분포 등) **[no]**
  - 각 단과대의 구체적 사업 내용과 예산 **[partial]**
  - 전교적 단과대별 비교 현황 **[no]**

**부족(missing):** 단과대별 교원 구성(정원, 직급, 전공분야) · 단과대별 주요 사업의 체계적 목록 · 단과대별 교원 현황을 보여주는 통계·표 · 단과대별 장기발전계획 또는 전략

**실제 봇 답변(발췌):**
> 제공된 위키 자료를 검토한 결과, **단과대별 주요 사업**과 **단과대별 교원 구성(학과별 교원 수 등 세부 데이터)**은 현재 제공된 자료 범위 내에 포함되어 있지 않습니다.
> 
> ---
> 
> ## 제공된 자료에서 확인 가능한 관련 정보
> 
> ### 🏫 단과대학 목록 (15개)
> 
> 제공된 조직도 기준으로 단과대학 명칭만 확인됩니다 [대학현황 서울대학교 조직도 개요](/wiki?agent=status&type=facts&id=%EC%A1%B0%EC%A7%81%EB%8F%84-%EA%B0%9C%EC%9A%94.fact):
> 
> | 단과대학 | 학과(부) 수 |
> |---|---|
> | 인문대학 | 16개 학과 |
> | 사회과학대학 | 9개 |
> | 자연과학대학 | 7개 |
> | 공과대학 | 11개 |
> | 농업생명과학대학 | 8개 |
> | 사범대학 | 15개 |
> | 경영대학 | 1개 |
> | 생활과학대학 | 3개 |
> | 간호
>   […중략…]
>   tor of Philosophy로 수정) [평의원회] 18기-13차
>   - **첨단융합학부**: 신설·운영, 5개 전공 학생 배정, 첨단기자재 도입 [대학운영계획] 2026-운영계획-실행과제1
> 
> ---
> 
> 단과대별 세부 정보가 필요하시다면 서울대학교 공식 홈페이지(snu.ac.kr) 또는 각 단과대 홈페이지를 직접 확인하시는 것을 권장드립니다. 특정 단과대나 사업에 대해 더 좁혀서 질문해 주시면, 제공된 자료 범위 내에서 최대한 답변드리겠습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [33] 모델: `opinion-grounded`  ·  42자 · tier1 · 위키: senate, board, plan, vision, finance, status, history

**Q:** 현재 서울대학교 전임교원의 연간 교과목 담당 시수는 어떤 근거로 결정되는가?

**평가자 aspect 판정:**
  - 전임교원 연간 교과목 담당 시수 결정의 근거·기준 **[partial]**
  - 교과목 담당 시수 관리 체계 및 운영 지침 **[yes]**
  - 시수 결정 시 적용되는 감면·조정 규칙 **[yes]**
  - 시수 결정 권한자 및 의사결정 프로세스 **[no]**

**부족(missing):** 기본 책임시수 액수 또는 단과대학별 차등 기준 · 시수 결정 최종 권한(단과대학장/학과장/중앙부서 중 누가) · 편성 절차 및 의사결정 단계

**실제 봇 답변(발췌):**
> ## 전임교원 책임시수 결정 근거
> 
> ### 📋 규정 체계: 「전임교원 책임시간 운영 지침」
> 
> 전임교원의 연간 교과목 담당 시수는 **「서울대학교 전임교원 책임시간 운영 지침」**에 근거하여 결정됩니다 [평의원회] 19기-4차.
> 
> 이 지침은 2026년 2월 평의원회 보고 안건으로 제출된 **「전임교원 책임시수 관리체계 개선(안)」**을 통해 그 내용이 확인되며, 주요 구조는 다음과 같습니다 [평의원회] 19기-4차:
> 
> ---
> 
> ### 📐 책임시수 산정 기준 (지침 제3조)
> 
> **제3조 제1항 — 감면 대상 및 방식**
> 
> | 구분 | 내용 |
> |---|---|
> | **별표 명시 대상** | 별표에 규정된 감면 대상에 해당하는 경우 시수 감면 |
> | **신규 임용 교원** | 강의 담당 학기부터 **1년간** 총 6시간 감면 (육아휴직 기간은 산입하지 않음) |
> | **여성 교원** | 출산 학기 또
>   […중략…]
>   입 문제**: 제3조 제1항 제2호 관련하여, 육아휴직 기간뿐만 아니라 **출산휴가 기간도 산입하지 않도록** 하는 것이 조항 취지에 부합한다는 의견이 제기되었고, 교무처는 검토를 답변했습니다.
> 
> ---
> 
> ### 📝 한계 안내
> 
> 제공된 자료에는 **책임시수의 구체적 총량(예: 연간 몇 학점)** 또는 직위별(교수·부교수·조교수) 차등 기준에 대한 수치는 포함되어 있지 않습니다. 상세 수치는 지침 별표 및 본문 전체를 별도로 확인하시기 바랍니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [34] 모델: `opinion-grounded`  ·  41자 · tier1 · 위키: plan, senate, board, vision, status

**Q:** SNU Holdings와 서울대기술지주회사의 차이와 충돌 지점을 설명해줘.

**평가자 aspect 판정:**
  - SNU Holdings의 정의, 역할, 기능 **[yes]**
  - 서울대기술지주회사의 정의, 역할, 기능 **[partial]**
  - 두 기관 간의 관계(지분인수, 통합 등) **[partial]**
  - 두 기관 간의 충돌 지점이나 역할 중복 **[no]**

**부족(missing):** 서울대기술지주회사의 구체적 정의·기능·조직 현황 · 두 기관의 충돌 지점, 역할 분담의 경계, 실질적 갈등 사항

**실제 봇 답변(발췌):**
> # SNU Holdings와 서울대 기술지주회사: 역할 구분과 관계
> 
> ## 🏗️ 두 기관의 기본 성격
> 
> **SNU Holdings (에스엔유홀딩스)**는 서울대학교의 지적재산·인적·물적 자원을 활용한 **신사업 발굴 및 자회사 설립·운영을 총괄**하는 수익사업 컨트롤타워입니다 [대학운영계획] 2026-운영계획-실행과제12 [중장기발전계획] 중장기-제2장-재정. 여러 법인·기관에 분산된 수익사업 유사 기능을 통합하고 규모의 경제를 실현하기 위해 설립되었으며 [중장기발전계획] 중장기-제2장-재정, 산하에 **SNU 벤처스** 등 자회사를 두고 있습니다 [대학운영계획] 2026-운영계획-실행과제12.
> 
> **서울대 기술지주회사**는 이와 별개로 존재하는 기관으로, 대학 보유 기술의 이전·사업화를 위해 설립된 전통적인 산학협력 모델의 법인입니다.
> 
> ---
> 
> ## 🔗 양 기관의 관계 — 통합 추진 중
> 
> 현
>   […중략…]
>   상위 지주 구조**로 설계되어 있으나, 지분인수가 완료되기 전까지 두 기관은 병존하며 기능 중복과 거버넌스 정보 비대칭이라는 긴장을 내포합니다. 2026년 상반기 지분인수 완료가 이 긴장을 해소하는 분기점이 될 것으로 보입니다 [대학운영계획] 2026-운영계획-실행과제12.
> 
> > **📌 한계**: 기술지주회사의 독립적 운영 실적, 지분인수 협상 경과, 양 기관 간 내부 갈등의 구체적 내용은 제공된 자료 범위 내에 상세히 기록되어 있지 않습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [35] 모델: `opinion-grounded`  ·  40자 · tier1 · 위키: senate, board, plan, history, status, vision, finance, yhl-speeches

**Q:** 미래의 대학 모습은 어때야 하며 서울대학교는 어떠한 준비를 하고 있는지?

**평가자 aspect 판정:**
  - 미래 대학의 바람직한 모습에 대한 서울대의 비전·철학 **[partial]**
  - 서울대가 미래 대학 준비를 위해 구체적으로 추진 중인 사업·계획 **[yes]**
  - 미래 대학 구현을 위한 조직·제도적 변화 **[yes]**
  - 외부 대학·국제 트렌드와의 비교를 통한 서울대의 상대적 위치 **[no]**

**부족(missing):** 미래 대학의 이상적 모습에 대한 명시적 철학·가치관 진술 · 외부 대학/국제기관과의 비교 분석

**실제 봇 답변(발췌):**
> # 🔭 미래 대학의 모습과 서울대학교의 준비
> 
> ---
> 
> ## 1. 미래 대학은 어떤 모습이어야 하는가
> 
> ### 🌐 문명사적 전환에 대응하는 학문공동체
> 
> 서울대 중장기발전계획은 미래 대학의 존재 이유를 명확히 정의합니다:
> 
> > **"국가와 인류의 미래에 공헌하는 지식공동체"** [중장기발전계획] 중장기-제1장
> 
> 급격한 과학기술 발전과 정치·경제적 불확실성이 높아지는 **대전환(Great Transformation)의 시대**에, 대학은 이 전환을 **이끌어가는** 능동적 주체여야 한다는 것입니다 [대학현황 서울대학교 비전](/wiki?agent=status&type=facts&id=%EB%B9%84%EC%A0%84.fact).
> 
> ### 📐 미래 대학의 3대 조건
> 
> 중장기발전계획이 제시하는 미래 대학의 핵심 요건은 다음과 같습니다 [중장기발전계획] 중장기-제1장:
> 
> | 조건 | 내용 |
> |---|-
>   […중략…]
>   학으로 전환했던 서울대가 [70년역사] 연구중심대학을-향하여 [70년역사] 연구중심대학-후-교육운영-변화, 이제는 **융합·AI·난제 해결형 지식공동체**로 두 번째 대전환을 추진하고 있습니다 [유홍림총장연설] 취임사-2023 [유홍림총장연설] 신년사-2026.
> 
> ---
> 
> ⚠️ **자료 한계**: 위 내용은 공개된 공식 계획·의사록·연설 자료 기반입니다. 각 사업의 실제 집행 속도나 내부 구성원 반응 등 비공개 정보는 자료 범위 밖에 있습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [36] 모델: `opinion-grounded`  ·  40자 · tier1 · 위키: board, senate, status, history, yhl-speeches, plan

**Q:** 이석재 총장 후보자와 서울대의 주요 사업 중 핵심적으로 일치하는게 있어?

**평가자 aspect 판정:**
  - 이석재 개인의 정책 입장·비전·전문성 영역 **[no]**
  - 서울대학교의 주요 사업·전략 분야 (2024~2026) **[yes]**
  - 이석재와 서울대 주요 사업 간의 일치·부합 정도 **[no]**

**부족(missing):** 이석재의 교육·연구·경영 철학 및 주요 관심 분야 · 이석재의 대학 거버넌스·발전 방향에 대한 공식 입장서나 면접 기록 · 이석재와 서울대 주요 사업(AI대학원, 미래연구진흥센터, 배곧병원, 학부대학, ERP, 장기발전계획 등) 간의 구체적 연계 관점

**실제 봇 답변(발췌):**
> # 이석재 후보자와 서울대 주요 사업의 핵심 일치 분석
> 
> ## ⚠️ 분석의 전제와 한계
> 
> 70년역사 위키에 이석재 후보자의 stance 태그들이 존재하나, **stance 문서 본문이 현재 제공된 자료 범위에 포함되어 있지 않습니다.** 따라서 후보자의 구체적 발언·공약 내용은 확인할 수 없고, **stance 태그의 주제명**과 서울대 공식 사업명의 **주제적 대응 관계**만 분석 가능합니다.
> 
> 이 점을 전제로, 태그 주제명 기준 일치 여부를 정리합니다.
> 
> ---
> 
> ## 🔬 연구 분야
> 
> | 이석재 후보 stance 태그 | 서울대 공식 사업 | 일치 강도 |
> |---|---|---|
> | `학문후속세대지원` | 실행과제 4 "우수 학문후속세대 육성" — 기초학문·특성별 발굴·지원, 학사-대학원 연계과정 확대 [대학운영계획] 2026-섹션3 | ⭐⭐⭐ 명칭 수준 일치 |
> | `중장기연구이니셔티브`
>   […중략…]
>   계획] 2026-섹션3
> 
> 3. **🌐 국제화 전략** — 후보자 태그 `국제화전략`이 2026 신년사에서 3대 신규 사업 중 하나로 명시된 "국제화 전면 개편"과 일치 [유홍림총장연설] 신년사-2026
> 
> ---
> 
> > **⚠️ 재확인 필요사항**: 위 분석은 stance 태그 **주제명**과 서울대 공식 사업명의 대응에 기반합니다. 이석재 후보자가 각 주제에서 구체적으로 어떤 입장을 취하는지는 stance 문서 본문이 제공되어야 확인 가능합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [37] 모델: `opinion-grounded`  ·  40자 · tier1 · 위키: senate, plan, board, history, vision, status

**Q:** 서울대학교의 상황에서 교양 강화가 맞나 전공 교육 조기진입/심화가 맞나?

**평가자 aspect 판정:**
  - 교양 강화 vs 전공 교육 조기진입/심화 중 어느 것이 서울대의 현황·정책인가 **[partial]**
  - 두 방향 중 어느 것이 옳은지에 대한 대학 지도부·평의원회의 공식 판단·결정 **[partial]**
  - 두 방향의 장단점 분석 및 비교 평가 **[no]**
  - 향후 서울대의 교육 방향 선택에 대한 전망·권고 **[no]**

**부족(missing):** 교양 강화와 전공 조기진입/심화 중 대학이 최종 선택한 기본 방향 · 두 접근법의 장단점에 대한 객관적 비교 분석 · 향후 교육정책의 방향성에 대한 대학 지도부의 명시적 입장

**실제 봇 답변(발췌):**
> # 서울대학교 맥락에서: 교양 강화 vs. 전공 조기진입·심화
> 
> 이 질문은 단순한 교육철학 논쟁이 아니라, **서울대 내부에서 실제로 충돌하고 있는 긴장 관계**입니다. 자료에서 양쪽 논거를 모두 추출하면 다음과 같습니다.
> 
> ---
> 
> ## ⚖️ 핵심 긴장 구도
> 
> | 입장 | 논거 | 주체 | 출처 |
> |---|---|---|---|
> | **교양 강화** | 학부=교양 토대, 전공 심화=대학원 | 연구중심대학 전략 전반 | [70년역사] 연구중심대학-후-교육운영-변화 |
> | **교양 강화** | 융합·초학제 교육의 공통 기반 필요 | 중장기발전계획·유홍림 총장 | [중장기발전계획] 중장기-제2장-교육 |
> | **교양 강화** | AI 시대 인간적 역량은 교양이 담당 | 유홍림 총장 | [유홍림총장연설] AI시대대학역할 |
> | **전공 조기진입** | 첨단분야 전문인재 양성엔 조기 전공 필요 | 첨
>   […중략…]
>   회] 17기-21차, 17기-22차, 17기-23차, 18기-16차
> 
> ---
> 
> **한계 고지**: 실제 재학생의 학습 성과 데이터, 졸업생 추적 연구, 타 대학 비교 데이터는 제공된 자료에 포함되어 있지 않아 실증적 효과 비교는 불가합니다.
> 
> 더 깊이 들어갈 주제가 있으시면 알려주세요. 예: **"첨단융합학부 설립 과정에서 평의원회와 본부의 충돌 전체 경과"** 또는 **"학부대학이 기초교육원을 대체한 이유와 논란"** 등으로 연결 가능합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [38] 모델: `opinion-grounded`  ·  38자 · tier1 · 위키: senate, board, finance, vision, status, plan, history

**Q:** 평의원회는 서울대 규정 상 정해지지 않은 권한을 행사하는 것 아니야?

**평가자 aspect 판정:**
  - 평의원회의 규정상 권한(법적 근거) **[partial]**
  - 평의원회가 실제 행사한 규정 밖의 권한 사례 **[no]**
  - 규정 미명시 권한의 법적 정당성 여부 **[no]**

**부족(missing):** 평의원회가 규정에서 명시되지 않은 권한을 구체적으로 행사한 사례 · 그러한 권한 행사의 법적·규정상 정당성 논거 · 평의원회 규정과 실제 행사 권한 간의 괴리에 대한 명확한 판단

**실제 봇 답변(발췌):**
> # 평의원회 권한의 법적 근거와 '월권' 논란 검토
> 
> 좋은 질문입니다. 자료를 면밀히 검토하면, 이 문제는 단순히 "월권이냐 아니냐"가 아니라 **규정의 해석 범위와 절차적 정당성**을 둘러싼 긴장으로 보입니다.
> 
> ---
> 
> ## ⚖️ 1. 평의원회의 법적 근거는 실제로 존재한다
> 
> 평의원회의 권한 근거는 명확합니다:
> 
> - **정관 제18조 제2항 제4호**: "학과 신설 등은 평의원회 심의 사항" [평의원회] 18기-4차
> - **서울대법 제9조 제1항**: 이사 추천권 — 평의원회가 직접 투표로 이사 후보 선출 [평의원회] 17기-22차, 18기-19차
> - **정관 규정 심의기구**로 명시 [대학현황] 조직도-개요.fact
> 
> 즉 평의원회는 **정관과 서울대법에 근거한 법정 기구**이며, 심의권 자체는 규정에 명시되어 있습니다.
> 
> ---
> 
> ## ⚠️ 2. 그러나 "심의"의 범위·효력을 둘러싼 긴장이
>   […중략…]
>   능하는 것이 설계 의도인지 여부 |
> | **현재 상태** | 이사회가 2025년에야 평의원회 의결 요청 사안 범위를 **별도로 확정** — 경계 자체가 최근까지 불명확했음 |
> 
> > **결론**: 평의원회의 권한 행사는 규정상 근거가 있습니다. 다만 **심의 결과의 구속력과 이사회와의 위계가 명확하지 않은 것**이 문제이며, 이는 평의원회의 문제라기보다 **법인화 설계 당시부터 해소되지 않은 구조적 모호성**으로 보는 것이 자료에 더 부합합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [39] 모델: `opinion-grounded`  ·  38자 · tier1 · 위키: senate, history, status, yhl-speeches, finance, board

**Q:** 실제 자료들 중에서 위 공약들을 수립할 때 참고할만한 자료가 있을까?

**평가자 aspect 판정:**
  - 질문의 '공약'이 무엇을 지칭하는지 명확화 **[no]**
  - 공약 수립 시 참고할 수 있는 서울대 자체 자료·기록의 존재 여부 **[partial]**
  - 구체적으로 어떤 자료들이 공약 수립에 참고될 수 있는지의 사례·목록 **[partial]**

**부족(missing):** 질문의 '공약'이 정확히 무엇을 의미하는지(예: 총장 공약, 평의원회 정책 공약, 학칙 개정안 등) · 공약 수립 프로세스에서 위키 자료를 실제로 어떻게 활용해야 하는지에 대한 가이드라인 · 공약과 관련된 구체적인 선례나 성공 사례

**실제 봇 답변(발췌):**
> 이 주제에 대한 이석재 후보의 명시적 입장 자료가 없습니다. 일반 자료 기반으로 답변합니다.
> 
> ---
> 
> # 이석재 후보 공약 수립 시 참고할 만한 자료
> 
> 제공된 자료 중 이석재 후보의 주요 공약과 직접적으로 연결되는 내용을 주제별로 정리합니다.
> 
> ---
> 
> ## 🎓 박사과정생 처우 · 연구실 문화 공약 관련
> 
> ### 이공계 연구생활장려금 현황 — 현실적 한계 확인
> 
> [평의원회] 18기-21차 자료는 공약의 **문제의식을 뒷받침하는 핵심 근거**가 됩니다.
> 
> > 당초 예상 약 1,000명 → 실제 9월 지급 대상 약 **100명** (세부 요건 반영 결과)
> > — [평의원회] 18기-21차
> 
> 즉, 현재 이공계 연구생활장려금 제도가 존재하지만 **실제 수혜자가 예상의 10%에 불과**한 상황입니다. "박사과정생 전원 월 150만원 보장"이라는 공약의 현실적 필요성을 직접적으로 뒷받침하는 데이터입니다.
>   […중략…]
>   [70년역사] 연구비-역사 | 역사적으로 연구비 항상 부족했음 |
> | 구성원 참여 거버넌스 | [평의원회] 18기-17차 | 심의기구 축소 반대 표결 선례 |
> | AI 교육·연구 가이드라인 | [평의원회] 18기-21차 | 제도화 절차의 선례 |
> 
> ---
> 
> **자료 한계**: 현재 제공된 자료는 평의원회 일부 회의록과 70년사 일부 챕터에 한정됩니다. 재무정보, 이사회, 중장기발전계획 자료가 추가로 활용된다면 더 풍부한 근거 수집이 가능합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [40] 모델: `opinion-grounded`  ·  38자 · tier1 · 위키: senate, board, history, status, finance

**Q:** 대학원생 관련 후보자 의견은과 현재 대학원생에 대한 서울대의 실태는?

**평가자 aspect 판정:**
  - 대학원생 관련 총장 후보자의 의견 **[no]**
  - 현재 서울대의 대학원생 실태(규모, 지원, 처우, 정책 등) **[no]**
  - AI대학원 등 신설 대학원의 계획 **[yes]**
  - 대학원생 관련 거버넌스/심의 사항 **[partial]**

**부족(missing):** 총장 후보자의 대학원생에 대한 의견·정책 제안 · 현재 서울대 대학원생의 규모, 처우, 지원 현황, 문제점 등 실태 · 대학원생 관련 학칙·규정·정책 논의

**실제 봇 답변(발췌):**
> # 대학원생: 이석재 후보의 입장 vs. 서울대 현황
> 
> ---
> 
> ## 👩‍🎓 현재 서울대 대학원생 규모
> 
> [대학현황] 현황.fact에 따르면, 2025년 4월 기준 서울대 재학생 총 **30,323명** 중 대학원생은 다음과 같습니다.
> 
> | 과정 | 인원 |
> |---|---|
> | 석사과정 | 6,919명 |
> | 박사과정 | 6,125명 |
> | **대학원 합계** | **13,044명** |
> | (학사과정) | (17,279명) |
> 
> 전체 재학생의 약 **43%**가 대학원생으로, 서울대는 연구 중심 대학으로서 대학원 비중이 매우 높은 구조입니다. [대학현황] 현황.fact
> 
> ---
> 
> ## 📋 이석재 후보의 대학원생 지원 입장
> 
> ### 1. 패러다임 전환: "값싼 연구 노동력" → "공동 연구자"
> 
> 이석재 후보는 현재 대학원생 처우 문제의 핵심을 **인식 자체의 문제**로 진단합니다.
> 
> > "이제
>   […중략…]
>    | 별도 자료 없음 | 박사 전원 등록금+월 150만 원 (5년 계획) |
> | 재원 조달 | 2024년 예산 법인회계 약 1.1조 원 [대학현황] 현황.fact | 발전기금 출연금 우선 배분 |
> 
> 서울대의 현황 자료에는 대학원생 처우·생활비·연구 문화에 관한 세부 데이터가 포함되어 있지 않아, 실태의 정량적 비교에는 한계가 있습니다. 이석재 후보의 입장은 현재 서울대 대학원 운영 현황 문서보다는 대담 자료([대담-1부])에 근거하고 있습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [41] 모델: `opinion-grounded`  ·  37자 · tier1 · 위키: plan, board, senate, history, vision, status

**Q:** 신임교수들에게 가장 중요한 교육 및 연구에서의 지원은 어떤 것일까?

**평가자 aspect 판정:**
  - 신임교수에게 제공되는 교육 지원의 구체적 내용 및 프로그램 **[partial]**
  - 신임교수에게 제공되는 연구 지원의 구체적 내용 및 규모 **[yes]**
  - 신임교수들이 가장 중요하게 여기는 지원이 무엇인지에 대한 우선순위 또는 선호도 평가 **[no]**
  - 신임교수 지원의 효과성 또는 만족도에 대한 평가 **[no]**

**부족(missing):** 신임교수의 교육 지원 프로그램 상세 내용 · 신임교수들의 지원 우선순위/선호도 조사 또는 의견 · 지원 효과성 및 만족도 평가 데이터

**실제 봇 답변(발췌):**
> # 🎓 신임교수에게 가장 중요한 교육·연구 지원
> 
> 제공된 위키 자료를 바탕으로, 신임교수 지원과 관련된 내용을 체계적으로 정리합니다.
> 
> ---
> 
> ## 🔬 연구 지원
> 
> ### 1. 연구 정착 지원
> - **연구정착금** 지원: 신임교원 104건 / 93.2억원 규모로 지원된 바 있음 [대학운영계획] 2026-섹션1-운영방향
> - **창의·도전적 연구과제** 지원: 101건 / 54.2억원 — 초기 독립 연구 기반 마련에 직결 [대학운영계획] 2026-섹션1-운영방향
> - **미래신진연구자(박사후연구원)** 지원: 27건 / 17.7억원 — 연구팀 구성 초기 단계 지원 [대학운영계획] 2026-섹션1-운영방향
> 
> ### 2. 선(先)연구-후(後)행정 문화 구축
> - 신임교수가 가장 취약한 시기에 **행정 부담 없이 연구에 집중**할 수 있는 환경 조성이 중장기 전략 방향으로 명시됨 [중장기발전계획] 중장기-
>   […중략…]
>    생활지원 장학금 신설** 방향 [중장기발전계획] 중장기-제2장-학생지원 — 신임교수와 연구팀 구성원(대학원생) 모두의 안정성 강화
> 
> ---
> 
> ## ⚠️ 자료 한계
> 
> 현재 제공된 자료는 신임교수 지원을 **별도 항목으로 체계화한 문서**를 포함하고 있지 않으며, 위 내용은 대학운영계획·중장기발전계획·이사회·평의원회 자료에 분산된 내용을 종합한 것입니다. 신임교수 대상 온보딩 프로그램, 멘토링 제도 등 세부 운영 내용은 자료 범위 밖에 있습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [42] 모델: `opinion-grounded`  ·  37자 · tier1 · 위키: senate, vision, finance, history, status, plan

**Q:** 대학원생 처우의 가장 큰 이슈는 무엇인가? 연구비는 얼마나 늘었나?

**평가자 aspect 판정:**
  - 대학원생 처우의 가장 큰 이슈가 무엇인가 **[partial]**
  - 연구비가 얼마나 늘었는가(증가율/규모) **[partial]**

**부족(missing):** 대학원생 처우의 '가장 큰' 이슈에 대한 명시적 우선순위 판정 · 최근 연구비 증가 추이에 대한 구체적 수치(특히 시계열 비교 데이터)

**실제 봇 답변(발췌):**
> # 대학원생 처우 현황과 연구비 증가 추이
> 
> ---
> 
> ## 🎓 대학원생 처우의 주요 이슈
> 
> ### 1. 박사과정 지원율 저하와 생활 여건
> 
> 대학원 지원율 저하가 심각하며, 특히 박사과정에서 두드러집니다. 장학금 확대와 안정적 생활조건 마련이 시급한 과제로 지목되었고, 기초학문 분야에 대한 대학본부 차원의 지원책 마련도 절실한 상황입니다 [중장기발전계획] 중장기-제2장-교육.
> 
> 중장기발전계획은 서울대 전임교원(정교수 기준) 급여가 국내 주요대학 평균의 **73% 수준**에 불과하여 우수 교원 확보·유지가 어렵다는 점도 함께 지적하고 있습니다 [중장기발전계획] 중장기-제2장-학생지원. 이는 연구 지도 환경 전반에 영향을 미치는 구조적 문제입니다.
> 
> ### 2. 외국인·장애 대학원생 지원 미흡
> 
> 외국인 학위과정생은 전체의 4.5%(1,260명)에 불과하고 10년간 정체 상태이며, 장애학생 등록 수는 
>   […중략…]
>   3년부터 연간 200억씩 누적되어 **2032년 이후 매년 2,000억원** 수준에 달할 것으로 계획하고 있습니다 [중장기발전계획] 중장기-제2장-재정.
> 
> ---
> 
> > **💡 종합 시사점**: 연구비는 양적으로 크게 성장했지만, 그 성과가 대학원생 처우 개선으로 연결되는 구조적 선순환은 아직 미흡합니다. 중장기발전계획은 이 격차를 인식하고 대학원생 장학금·생활비 지원 확대를 명시적 과제로 제시하고 있습니다 [중장기발전계획] 중장기-제2장-교육.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [43] 모델: `opinion-grounded`  ·  37자 · tier1 · 위키: senate, board, finance, vision, plan, history, status

**Q:** 최근 5년간 서울대 재정상황에서 주목할만한 게 어떤게 있는지 알려줘

**평가자 aspect 판정:**
  - 최근 5년간(2021~2026) 서울대 재정 규모·변화·주요 지표 **[partial]**
  - 주목할만한 재정 사건·정책 변화·의사결정 **[partial]**
  - 재정 상황의 원인·배경·맥락(국가정책, 외부환경 등) **[no]**
  - 향후 재정 전망·진단·평가 **[no]**

**부족(missing):** 구체적 재정 규모(수입·지출·결산액)의 연도별 추이 · 재정 상황의 양호/악화 여부에 대한 진단 또는 평가 · 대외 재정 환경(정부지원금 추이, 등록금 정책 등) 변화 · 향후 재정 전망·경고·권고사항

**실제 봇 답변(발췌):**
> # 서울대학교 최근 5년(2020~2024) 재정 주요 동향
> 
> ---
> 
> ## 💰 1. 종합 재정 규모의 지속 성장
> 
> 종합 운영수익(4개 주체 연결 기준)은 꾸준히 증가했습니다.
> 
> | 연도 | 종합 운영수익(억원) | 전년비 |
> |---|---|---|
> | 2020 | 15,875 | — |
> | 2021 | 17,922 | +13.0% |
> | 2022 | 18,842 | +5.1% |
> | 2023 | 21,384 | +13.5% |
> | 2024 | 21,438 | +0.3% |
> 
> 5년간 종합 수익이 약 **35% 성장**했습니다. [재무정보공시] 주체별-운영수익.fact
> 
> ---
> 
> ## 📈 2. 법인회계 예산 1조원 돌파 및 지속 확대
> 
> 법인회계 세입·세출 예산 기준으로:
> - 2024년도: **1조 563억원** (전년 대비 577억 증가) [이사회] 2024-1차
> - 2025년도: **1조 1,
>   […중략…]
>   %)는 여전히 높은 반면**, 산학협력단의 외부 연구수주 성장과 법인 자체 수익 개선으로 재정 구조는 다변화 추세입니다. 다만 발전재단(기부금) 비중 정체와 등록금 동결 기조는 자체재원 확충의 구조적 한계로 남아 있습니다. [재무정보공시] 주체별-운영수익.fact, [이사회] 2024-1차 (재정 비교 보고)
> 
> 특정 연도나 항목(예: 적립금 운용, 연구비 세부 출처, 발전재단 기금 운용)에 대해 더 구체적으로 궁금한 점이 있으면 질문해 주세요.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [44] 모델: `opinion-grounded`  ·  37자 · tier1 · 위키: plan, vision, status, history, yhl-speeches

**Q:** 미션I 수립에 있어 ‘융합적 인재’에 대한 정의 혹은 규정이 있나?

**평가자 aspect 판정:**
  - 미션I의 명칭 및 기본 정의 **[yes]**
  - '융합적 인재'에 대한 명시적 정의 또는 규정 **[partial]**
  - '융합적 인재'의 구체적 역량·속성·요건 기술 **[partial]**
  - '융합적 인재' 양성을 위한 실행 과제 및 프로그램 **[yes]**

**부족(missing):** '융합적 인재'에 대한 정형화된 정의문 또는 공식 규정 문서 · '융합적 인재'가 갖춰야 할 핵심 역량의 명시적 범주화

**실제 봇 답변(발췌):**
> # 미션 I '융합적 인재'의 정의·규정
> 
> 제공된 자료에서 **'융합적 인재'에 대한 단일·명시적 정의문**은 발견되지 않습니다. 다만 여러 자료에 걸쳐 그 내용이 **층위별로 규정**되어 있습니다.
> 
> ---
> 
> ## 📘 중장기발전계획 — 역량 목록으로서의 정의
> 
> 중장기발전계획은 '글로벌 리더 양성'을 3대 임무 중 첫 번째로 제시하면서, 융합적 인재가 갖춰야 할 역량을 다음과 같이 나열합니다:
> 
> > **창의성 · 수월성 · 공감 · 협업능력**을 갖춘 국제적 리더 [중장기-제1장]
> 
> 또한 WEF가 제시한 미래 16개 역량(기초문해력·능력·인성)을 배경으로, 전공 간 장벽 제거와 초학제적 교육과정 개발을 그 제도적 구현 방식으로 제시합니다 [중장기-제1장].
> 
> ---
> 
> ## 🎓 대학운영계획 — 실행과제 구조 속의 암묵적 정의
> 
> 2026년도 운영계획은 미션 I의 5개 실행과제(①~⑤) 자체가 융합적
>   […중략…]
>   ·수월성·공감·협업능력 |
> | **제도 구조** | 대학운영계획 | 5개 실행과제의 복합체 |
> | **철학적 규정** | 유홍림 총장 연설 | 통합적 사고 + 사회적 책임 + 협력적 리더십 |
> 
> ---
> 
> > **한계**: 세 자료 모두 '융합적 인재'를 **단일 문장으로 집약한 정의문**은 제시하지 않습니다. 공식 정의가 별도 문서(예: 교육비전 선언문, 학사제도 개편안)에 존재할 가능성은 있으나, 제공된 자료 범위 내에서는 확인되지 않습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [45] 모델: `opinion-grounded`  ·  36자 · tier1 · 위키: senate, board, vision, plan, finance, history, status

**Q:** 서울대 국제 경쟁력 강화를 위한 방안은 어떤 것들이 있는지 알려줘

**평가자 aspect 판정:**
  - 서울대 국제 경쟁력 강화를 위한 구체적 방안·정책·전략 **[no]**
  - 국제 경쟁력 관련 위원회·부서의 추진 현황 **[partial]**
  - 글로벌 협력·국제교류·대외 협약 등 구체 내용 **[partial]**

**부족(missing):** 국제 경쟁력 강화를 위한 구체적 방안·정책·전략 (위키에는 국제협력본부 조직 개편 논의와 국제협력협약 체결 기록만 있으며, 경쟁력 강화의 실질적 내용이 부재) · 글로벌 개발협력·ODA·학생 교환 등 구체적 국제교류 프로그램 · 세계 대학 순위·국제 평가 등 경쟁력 현황 진단

**실제 봇 답변(발췌):**
> ## 서울대학교 국제 경쟁력 강화 방안
> 
> ---
> 
> ### 🎓 1. 교육 국제화
> 
> **학사구조 개편**
> - 글로벌인재학부 신설 제안: 국제협력·국제통상·국제개발·국제보건·국제환경 등 다양한 영역에서 영어 강의 + 한국적 관점 이론 개발 [중장기발전계획] 중장기-제2장-국제화사회공헌
> - 장기 목표: 서울대 박사의 **20%**가 해외 기관에서 교육·연구 [중장기발전계획] 중장기-제2장-국제화사회공헌
> - 모집단위 광역화·전공선택 자율화, 문·이과 구분 폐지, 학제적·초학제적 교육과정 개발 [중장기발전계획] 중장기-제1장
> 
> **단기 국제교육 프로그램 확대**
> 
> | 프로그램 | 내용 |
> |---|---|
> | **ISP** (국제하계프로그램) | 영어 강의 교과목 + 한국문화 체험, K-Wave 수요 교과목 개발, 파트너 대학 교원 유치 |
> | **SWP** (세계 속 서울대) | 말레이시아·네팔·페루 대
>   […중략…]
>   환"** 을 명시적 방향 전환으로 제시했으며 [중장기발전계획] 중장기-제1장, 2026년 대학운영계획에서는 이를 구체적 프로그램(ISP 확대, EU 호라이즌 참여, SKERIC 후속사업 등)으로 실행 중입니다. 다만 평의원회는 국제처 조직 개편 시 "지원 기능에 한정"하고 ODA·KOICA 사업 별도 센터 신설은 부적절하다는 견제 의견을 제시하는 등 [평의원회] 18기-21차, 국제화 추진 방식에 대한 거버넌스 차원의 논의도 지속되고 있습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [46] 모델: `opinion-grounded`  ·  35자 · tier1 · 위키: finance, vision, history, status, yhl-speeches

**Q:** 서울대가 국고 의존 구조를 탈피하기 위해서는 어떻게 해야 하나?

**평가자 aspect 판정:**
  - 서울대의 현재 국고 의존 상황 진단 **[partial]**
  - 국고 의존 탈피의 구체적 전략·방안 **[partial]**
  - 대체 재원 확보 방향 및 목표 **[yes]**
  - 전략 실행의 현황·진척·평가 **[no]**

**부족(missing):** 국고 의존 탈피를 위한 구체적·실행적 방안 또는 실행 계획 · 현재까지의 탈피 노력에 대한 진척 평가 및 성과 분석 · 국고 의존도 개선의 타당성·실현성 진단

**실제 봇 답변(발췌):**
> ## 서울대 국고 의존 구조 탈피 방안
> 
> ---
> 
> ### 📊 현황 진단: 얼마나 심각한가?
> 
> **현재 의존 구조**
> 
> | 수입원 | 2017 | 2024 | 변화 |
> |---|---|---|---|
> | 정부출연금 비중 | 29.6% | 29.1% | △0.5%p |
> | 등록금 비중 | 12.7% | 9.2% | △3.5%p |
> | **정부 의존도 합산** | **42.4%** | **38.3%** | **△4.1%p** |
> | 산학협력수익 비중 | 35.6% | 38.8% | +3.2%p |
> | 기부금 비중 | 11.5% | 11.7% | +0.2%p |
> 
> [재무정보공시] 재원구조분석.fact
> 
> > 8년간 정부 의존도가 42.4% → 38.3%로 완만히 하락했으나, 법인(서울대) 단독 기준으로는 정부출연금이 여전히 운영수익의 **56.1%**를 차지 [재무정보공시] 법인-서울대학교
> 
> **구조적 
>   […중략…]
>   용 | 🟡 중간 | 🟡 중간 | 유형자산 유동화 한계 |
> | 등록금 현실화 | 🔴 낮음 | 🔴 낮음 | 정치·사회적 제약 |
> 
> 중장기발전계획이 스스로 인정하듯, 서울대의 국고 의존 구조는 **완전 탈피보다는 점진적 희석**이 현실적 경로입니다. 핵심은 산학협력수익의 **민간·해외 비중 확대**, 기부금의 **안정적 기반 구축**, 그리고 SNU홀딩스를 통한 **수익사업 다각화**를 동시에 추진하는 것입니다 [중장기발전계획] 중장기-제2장-재정.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [47] 모델: `opinion-grounded`  ·  34자 · tier1 · 위키: finance, plan, vision, history, status

**Q:** 이러한 다양한 비교과 프로그램은 어떤 방식으로 홍보되고 있나?

**평가자 aspect 판정:**
  - 비교과 프로그램의 홍보 방식·채널·전략 **[no]**
  - 비교과 프로그램의 종류·내용·운영 현황 **[partial]**
  - 홍보 예산·담당 부서·구체적 홍보 활동 **[no]**

**부족(missing):** 비교과 프로그램 홍보 방식(온라인/오프라인 채널, SNS 활용, 포스터, 설명회 등) · 홍보 담당 부서 및 조직 · 홍보 예산 규모 · 구체적 홍보 활동 사례 및 효과 · 학생 인지도·참여율 현황

**실제 봇 답변(발췌):**
> # 서울대학교 비교과 프로그램 홍보 방식
> 
> 제공된 자료에서 비교과 프로그램의 **홍보 방식**을 직접적으로 다루는 내용은 매우 제한적입니다. 다만, 관련 단서를 모아 정리하면 다음과 같습니다.
> 
> ---
> 
> ## 📢 자료에서 확인되는 홍보 수단
> 
> ### 1. 온라인 공개강좌 및 영상 플랫폼
> - **K-MOOC** 학습자 참여단 **`샤묵메이트`** 를 2025년부터 구성하여 강좌 홍보 및 학내외 구성원 참여 촉진에 활용하고 있습니다 [대학운영계획] 2026-운영계획-실행과제10.
> - **유튜브 `<샤로잡다>` 시리즈**: 2021년부터 총 46편 제작, 2025년 누적 조회수 **1,600만 회**를 기록한 지식나눔 영상으로, 대학 프로그램의 사회적 가시성을 높이는 역할을 합니다 [대학운영계획] 2026-운영계획-실행과제10.
> 
> ### 2. 국제 프로그램 홍보
> - **ISP(International
>   […중략…]
>   진 중으로 [대학운영계획] 2026-운영계획-실행과제5, 향후 성과 홍보 기반으로 활용될 예정입니다.
> 
> ---
> 
> ## ⚠️ 자료의 한계
> 
> 제공된 자료는 주로 **프로그램의 운영 내용·목표·예산**을 다루고 있으며, 교내 포털·학생처 공지·오리엔테이션·소셜미디어 운영 등 **일상적인 홍보 채널**에 대한 체계적인 기술은 포함되어 있지 않습니다. 구체적인 홍보 전략이나 채널별 운영 현황은 별도 자료(학생처 운영 보고 등)를 통해 확인이 필요합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [48] 모델: `opinion-grounded`  ·  33자 · tier1 · 위키: senate, board, finance, plan, vision, history, status

**Q:** 서울대 교수 처우 개선과 관련된 논의를 어떤 것들이 있었나?

**평가자 aspect 판정:**
  - 서울대 교수 처우 개선 관련 논의 여부 **[partial]**
  - 논의된 구체적 주제·내용 **[partial]**
  - 논의의 시기·회의 명칭 **[yes]**
  - 논의 결과·결정사항 **[partial]**

**부족(missing):** 교수 처우 개선의 구체적 내용(급여·복리후생 등)의 세부 논의 · 교수 처우 개선 관련 최종 결정·실행 방안 · 평의원회 외 다른 위원회의 교수 처우 개선 논의

**실제 봇 답변(발췌):**
> ## 서울대학교 교수 처우 개선 관련 논의
> 
> ---
> 
> ### 💰 급여 수준 문제 제기 (중장기발전계획)
> 
> 서울대 중장기발전계획(2022년 8월)에서 교수 처우 문제가 구조적 이슈로 명시적으로 다뤄졌습니다.
> 
> - **전임교원(정교수 기준) 급여가 국내 주요대학 교원 평균의 73% 수준**에 불과해 우수 교원 확보·유지에 어려움이 있다고 진단 [중장기발전계획] 중장기-제2장-학생지원
> - 세계적 석학(외국인 교원) 채용을 위한 임금·정주 여건 마련 필요성도 함께 제기 [중장기발전계획] 중장기-제2장-학생지원
> - 연구 방향에서도 **교원 처우개선·채용방식 개선**을 전략 과제로 제시 [중장기발전계획] 중장기-제2장-연구
> 
> ---
> 
> ### 📋 장기발전계획 논의 과정에서의 쟁점 (평의원회)
> 
> 2040 서울대학교 장기발전계획안을 평의원회에서 보고받는 과정에서 교원 처우 개선 문제가 의원들로부터 직접 제기되었
>   […중략…]
>   책자 제작을 약속 [평의원회] 17기-22차
> 
> ---
> 
> ### 📌 종합 시사점
> 
> 교수 처우 개선 논의는 **문제 인식(중장기계획) → 평의원회 제기(17기) → 정책연구(18기) → 연봉제 제도화(2025년)**의 흐름으로 진행되었습니다. 다만 급여 수준 자체의 절대적 인상보다는 **성과 연동 보수 체계 정비**에 초점이 맞춰졌으며, 처우 개선을 전략 계획의 전면에 내세우는 것에 대해서는 본부가 지속적으로 신중한 입장을 유지한 것이 특징입니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [49] 모델: `opinion-grounded`  ·  32자 · tier1 · 위키: board, vision, status, senate, history

**Q:** 지금까지 역대 총장의 대표 공약 사업들을 한번 정리해보자.

**평가자 aspect 판정:**
  - 역대 총장 명단 및 재임 기간 **[no]**
  - 각 총장별 대표 공약·주요 사업 내용 **[partial]**
  - 공약 사업의 추진 결과·성과 **[no]**
  - 시간순 정렬된 통합 정리 **[no]**

**부족(missing):** 역대 총장의 구체적 명단 및 재임 기간 · 각 총장의 취임 당시 공약 문서 또는 공식 발표 · 총장별 공약 사업의 추진·완료 현황 · 공약 사업 간 비교·분석을 위한 체계적 정리 · 28대 이전 총장들의 공약 내역

**실제 봇 답변(발췌):**
> # 서울대학교 역대 총장 대표 공약·역점 사업 정리
> 
> ## ⚠️ 자료 범위 안내
> 
> 제공된 위키 자료는 **총장별 공약·역점 사업을 직접 정리한 자료를 포함하고 있지 않습니다.** 다만 70년 역사, 중장기발전계획, 이사회·평의원회 자료를 교차 분석하여 **간접적으로 확인되는 사항**만 아래에 정리합니다.
> 
> ---
> 
> ## 📋 자료에서 간접 확인되는 총장별 주요 사업
> 
> | 총장 | 재임 시기 | 확인되는 주요 사업 | 근거 |
> |---|---|---|---|
> | **오세정** (제27대) | ~2023.2 | 중장기발전계획 수립 착수 (2021년 4월 직접 요청, 85명 위원 참여, 100회 이상 분과 회의, 2022년 8월 보고서 발간) | [중장기발전계획] 중장기-제1장 |
> | **유홍림** (제28대) | 2023.2~ | SNU 그랜드퀘스트, 초학제적 융합교육, AI 네이티브 캠퍼스, 학부대
>   […중략…]
>   기발전계획] 중장기-제1장)과 유홍림 총장(그랜드퀘스트·AI캠퍼스 등 [이사회] 2026-1차 [이사회] 2026-2차) 두 사례에 한정됩니다.
> 
> 역대 총장 전체의 공약·역점 사업을 체계적으로 정리하려면, 현재 제공된 위키 자료 범위 밖의 **총장 취임사, 연도별 대학운영계획, 각 총장 재임기 이사회 자료** 등이 추가로 필요합니다. 특정 총장이나 특정 시기에 대해 더 좁혀서 질문해 주시면 확인 가능한 내용을 최대한 상세히 안내해 드리겠습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [50] 모델: `opinion-grounded`  ·  32자 · tier1 · 위키: senate, board, finance, vision, plan, status

**Q:** 서울대 재무중에서 어떤 부분을 가장 시급하게 개선해야할까?

**평가자 aspect 판정:**
  - 서울대학교 재무 영역의 현황·구조·문제점 **[partial]**
  - 재무 개선의 우선순위 또는 개선 방향에 대한 진단·제언 **[no]**
  - 재정 관련 위원회(재경위원회)의 역할·권한·활동 **[partial]**

**부족(missing):** 재무 영역의 구체적 문제점 분석 또는 진단 의견 · 개선 우선순위 또는 개선 방향에 대한 기록된 판단 · 재무중(또는 재정 부서)이 직면한 시급한 과제의 공식 평가

**실제 봇 답변(발췌):**
> # 서울대 재무 구조: 시급한 개선 과제 분석
> 
> 위키 자료에 나타난 재무 데이터와 거버넌스 논의를 종합하면, 다음 네 가지 영역이 구조적 취약점으로 반복 확인됩니다.
> 
> ---
> 
> ## 💰 1. 정부출연금 과의존 — 재정 자율성의 핵심 리스크
> 
> | 항목 | 수치 | 출처 |
> |---|---|---|
> | 정부출연금·보조금 비중 (법인, 2024) | **56.1%** | [재무정보공시] 법인-서울대학교 |
> | 등록금 비중 (법인, 2024) | 17.8% | [재무정보공시] 법인-서울대학교 |
> | 법인 운영수익 총액 (2024) | 11,106억원 | [재무정보공시] 주체별-운영수익.fact |
> 
> 법인 수익의 절반 이상이 정부출연금에 묶여 있습니다. 평의원회는 이를 직접 문제로 제기했습니다.
> 
> > "「서울대법」 제30조제2항 근거로 **정부 출연금 확보 대책 요청**"
> > — [평의원회] 18기-4차
>   […중략…]
>   4위** | 산학협력단 수익 안정화 | 연구과제 의존 구조 + 내부거래 급변동 |
> 
> 대학운영계획은 발전재단 OCIO 수익률(2025년 연 9.5%, 누적 55.5%), SNU홀딩스 수익사업 확대 등 자체재원 확충 방향을 제시하고 있으나 [대학운영계획] 2026-운영계획-실행과제12, 이것이 정부출연금 의존 구조를 단기간에 대체하기는 어렵습니다. **예산 거버넌스 개선은 제도적으로 즉시 착수 가능한 영역**이라는 점에서 실행 우선순위가 높습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [51] 모델: `opinion-grounded`  ·  31자 · tier1 · 위키: board, senate, plan, yhl-speeches, status, history

**Q:** 유홍림 총장의 그랜드퀘스트 비전과 추진 방향을 설명해줘"

**평가자 aspect 판정:**
  - 유홍림 총장의 그랜드퀘스트 사업 정의 및 목표 **[partial]**
  - 그랜드퀘스트 추진 방향·전략·세부 계획 **[partial]**
  - 그랜드퀘스트 비전 제시의 핵심 의도·철학 **[no]**

**부족(missing):** 그랜드퀘스트의 구체적 추진 방향 및 세부 전략 (사업의 우선순위, 로드맵, 핵심 추진 과제 등) · 총장의 비전 선언문 또는 기조 발언의 핵심 메시지 · 그랜드퀘스트가 서울대의 장기 발전 전략에서 차지하는 위치·의미에 대한 명시적 설명

**실제 봇 답변(발췌):**
> # 유홍림 총장의 그랜드퀘스트 비전과 추진 방향
> 
> ## 🎯 핵심 비전: "질문 기반 연구대학"
> 
> 유홍림 총장이 2026년 직접 주도하여 공식 출범시킨 **SNU 그랜드퀘스트(Grand Quest)** 는 단순한 연구지원 사업이 아닌, 서울대의 연구문화 자체를 "답" 중심에서 **"질문" 중심**으로 전환하려는 전략적 이니셔티브입니다.
> 
> > "올해 연구 분야에서는 '질문 기반 연구대학'을 목표로 'SNU 그랜드 퀘스트(Grand Quest)' 사업을 시작합니다. 한국 사회와 인류가 직면한 난제 해결에 새로운 돌파구를 제시할 수 있는 도전적 질문을 발굴하여 이를 연구과제로 지원할 것입니다." [평의원회] 19기-4차
> 
> 2026년 입학식에서도 신입생들에게 직접 선언하며 [유홍림총장연설] 입학식-2026, 이사회 보고 [이사회] 2026-1차 및 평의원회 심의 [평의원회] 19기-4차를 거쳐 공식화했습
>   […중략…]
>   심의
>                         (인문사회 범위 조문 보완 → 서면재심의) [평의원회] 19기-5차
> ```
> 
> ---
> 
> **ℹ️ 시사점**: 그랜드퀘스트는 총장의 강한 의지로 빠르게 추진되었으나, 평의원회와의 사전 협의 부족이 반복적으로 지적되었습니다 [평의원회] 19기-5차 [평의원회] 19기-4차. 향후 인문사회 분야 포함 여부, 연간 지원 규모 확정, 1,000억원 규모 재원 조달 방안 등이 주요 후속 과제로 남아 있습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [52] 모델: `opinion-grounded`  ·  31자 · tier1 · 위키: senate, board, finance, history, plan, status

**Q:** 현재 서울대 펀드레이징 전략이나 재정 확충 방향을 알려줘

**평가자 aspect 판정:**
  - 현재 서울대 펀드레이징(모금) 전략 **[no]**
  - 현재 서울대 재정 확충 방향·계획 **[partial]**
  - 펀드레이징 또는 재정 다각화 관련 구체 사업·정책 **[no]**
  - 향후 재정 운영 원칙·목표 **[partial]**

**부족(missing):** 펀드레이징 전략(모금·기부금 확대 방안) · 재정 다각화 관련 구체 정책(산학협력 수익화, 자산 운용 등) · 차년도 예산 편성 시 평의원회 사전 개입 요구는 존재하나, 현재 확정된 펀드레이징·재정 확충 전략 문서 부재

**실제 봇 답변(발췌):**
> ## 서울대학교 펀드레이징 전략 및 재정 확충 방향
> 
> ---
> 
> ### 💰 재정 확충의 전략적 위상
> 
> 서울대는 **"재정기반 강화를 통한 자율성 확보"** 를 12대 실행과제 중 하나(과제 12)로 명시하고 있으며 [대학현황] 비전.fact, 법인회계·산학협력단·발전재단 3개 축을 통합 운영하는 체계를 구축했습니다 [대학운영계획] 2026-섹션3-추진성과및기본방향.
> 
> ---
> 
> ### 🏦 축 1: 법인회계 자체재원 확충
> 
> **예산 규모 및 추이**
> 
> | 구분 | 2023년 | 2024년 | 2025년 |
> |---|---|---|---|
> | 법인회계 합계 | 9,986억원 | 1조 564억원 | 1조 1,223억원 |
> | 국고출연금 | 5,775억원 | 6,129억원 | 6,588억원 |
> | 등록금수입 | 1,828억원 | 1,873억원 | 1,908억원 |
> | 수입대체경비 | 1,131억원 | 1,
>   […중략…]
>   으로 의존** (1946년 정부 대학교육비의 93.3% 차지)했으며 [70년역사] 재정-역사적-흐름, 1990년 발전기금 설립(장학회+학술연구재단 통합)을 계기로 모금 기반 재원 다변화가 시작되었습니다 [70년역사] 재원-확충-노력. 2011년 법인화 이후 **정부출연금 + 발전기금 + 간접비** 3원 구조로 정착되었고 [70년역사] II-운영편-overview, 현재는 여기에 **SNU홀딩스 수익사업**을 추가하는 4원 구조로 진화 중입니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [53] 모델: `opinion-grounded`  ·  28자 · tier1 · 위키: plan, senate, board, status, yhl-speeches

**Q:** AI시대를 선도하기 위한 서울대의 과제는 무엇인가?

**평가자 aspect 판정:**
  - AI시대 대응을 위한 서울대의 현재 전략·계획 **[yes]**
  - AI시대 선도를 위해 해결해야 할 구체적 과제·문제점 **[partial]**
  - 경쟁 대학(국내외)과의 비교를 통한 상대적 위치·격차 **[no]**
  - 향후 전망·성공 가능성에 대한 진단·평가 **[no]**

**부족(missing):** 경쟁 대학과의 비교 분석 · 전략 추진의 실현 가능성·성공 확률 진단 · AI 분야 시장·기술 트렌드 분석 · 구체적 문제점·도전과제의 명확한 진단

**실제 봇 답변(발췌):**
> ## AI 시대를 선도하기 위한 서울대의 과제
> 
> ---
> 
> ### 🤖 1. AI Native 캠퍼스 구축
> 
> 유홍림 총장은 2026년 신년사에서 **AI Native 캠퍼스**를 3대 신규 사업 중 하나로 공식 선언했습니다 [유홍림총장연설] 신년사-2026.
> 
> **인프라 구축 로드맵** [대학운영계획] 2026-운영계획-실행과제11:
> 
> | 연도 | 주요 내용 |
> |---|---|
> | 2026 | 광케이블 구축, 무선망 확충, GPU 서버 코로케이션, 시범구간 전환 |
> | 2027 | 관악캠퍼스 차세대 네트워크 전환, 망분리·보안정책 적용 |
> | 2028 | 유무선 융합 네트워크 완성, 연건캠퍼스 전환, **시흥캠퍼스 AI GPU센터 구축** |
> 
> **AI 공통인프라** [대학운영계획] 2026-운영계획-실행과제11:
> - GPU·LLM·Agent 제작 서비스 등 공통인프라 → 누구나 AI Agent를
>   […중략…]
>   과 간 갈등, 정원 증원 교육부 승인 |
> | 행정·문화 전환 | AI 가이드라인·챗봇 구축 진행 중 | 구성원 적응·책임 있는 활용 문화 정착 |
> 
> 서울대의 AI 시대 선도 과제는 **인프라(GPU센터·네트워크)·교육(AI대학원·첨단융합학부)·연구(그랜드퀘스트)·문화(가이드라인·캠퍼스 라이선스)** 4개 축이 동시에 진행 중이나, 평의원회에서 제기된 거버넌스 설계와 학과 간 갈등 해소가 핵심 선결 과제로 남아 있습니다 [평의원회] 19기-7차.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [54] 모델: `opinion-grounded`  ·  27자 · tier1 · 위키: senate, board, finance, plan, status, history

**Q:** 26년 서울대 이사회랑 평의원회 회의 기록 알려줘

**평가자 aspect 판정:**
  - 2026년 서울대 이사회 회의 기록 **[no]**
  - 2026년 서울대 평의원회 회의 기록 **[partial]**

**부족(missing):** 2026년 이사회 회의 기록 · 2026년 평의원회 회의 기록(19기-4차 이후 기록 없음)

**실제 봇 답변(발췌):**
> # 2026년 서울대학교 이사회 및 평의원회 회의 기록
> 
> ---
> 
> ## 🏛️ 이사회 (2026년)
> 
> ### 제1차 이사회 (2026-02-10)
> > 행정관 4층 대회의실 / 참석: 13/15명
> 
> **주요 의결 결과** (안건 11건):
> 
> | 구분 | 안건 | 결과 |
> |---|---|---|
> | 의결(우선) | 제10대 이사장 선출 — [[최창원]] | **전원 찬성** |
> | 보고 | SNU 그랜드 퀘스트 사업 추진 계획(안) | 접수 |
> | 추인 1 | 학칙 일부개정(패스트트랙 — 규정 개정 시 생략 절차 구체화) | 원안 추인 |
> | 추인 2 | 학칙 일부개정(입학정원 등) — **의과대학 학제개편** 포함 | 원안 추인 |
> | 추인 3 | 학칙 일부개정(창업휴학 — 최대 2년 → **3년** 연장) | 원안 추인 |
> | 의결 2 | 2025년도 법인회계 추경 예산(안) + 적립금 — 세입
>   […중략…]
>   | 미확인 |
> | 이사장 | 제10대 [[최창원]] (2026.2.10~) | — |
> | 주요 예산 | 2026년 1조 2,038억원 | — |
> | 핵심 안건 | AI대학원, 미래연구진흥센터, 총장선출, 의과대 학제개편 | — |
> 
> ---
> 
> **📌 자료 한계**: 제공된 위키 자료는 이사회 기준 2026년 1·2차(~2026.3.24)까지만 수록되어 있습니다. 이후 이사회 및 2026년 평의원회 본회의 회의록은 포함되지 않아 확인이 어렵습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [55] 모델: `external-needed`  ·  70자 · tier1 · 위키: board, senate, plan, vision, status

**Q:** AI 관련 연구나 프로젝트와 관련하여 서울대가 최근 카이스트에 밀리고 있다는 관측이 많은데, 이렇게 된 원인을 진단해 주세요.

**평가자 aspect 판정:**
  - 서울대의 AI 관련 연구·프로젝트 현황 및 역량 수준 **[partial]**
  - 카이스트의 AI 관련 연구·프로젝트 현황 및 역량 수준 **[no]**
  - 서울대 vs 카이스트 AI 분야 비교 평가 **[no]**
  - 서울대가 카이스트에 밀리게 된 원인 진단 **[no]**

**부족(missing):** 카이스트의 AI 관련 연구·프로젝트 현황 · 두 대학 간 AI 역량의 실제 비교 데이터(논문, 특허, 기금, 연구비 등) · 외부 평가·순위·언론 보도 등 제3자 평가 · 서울대가 '밀리고 있다'는 관측의 근거

**실제 봇 답변(발췌):**
> ## 질문의 전제에 대한 중요한 안내
> 
> 제공된 서울대학교 내부 거버넌스 자료(이사회 의사록, 평의원회 회의록, 대학운영계획, 중장기발전계획 등)에는 **"서울대가 AI 분야에서 KAIST에 밀리고 있다"는 내용이 포함되어 있지 않습니다.**
> 
> 이 자료들은 서울대 내부의 의사결정 기록이므로, 타 대학과의 비교 진단이나 경쟁 평가는 원래부터 다루지 않습니다. 따라서 해당 전제를 사실로 전제한 원인 진단은 제공된 자료 범위 밖의 내용으로, **답변이 불가능합니다.**
> 
> ---
> 
> ## 대신 자료 내에서 확인되는 것: 서울대 스스로 인식하는 AI 분야 과제
> 
> 다만, 위키 자료에서 확인되는 **서울대 내부의 AI 관련 논의와 과제 인식**은 다음과 같이 정리할 수 있습니다.
> 
> ### 🔬 AI 대학원 — 뒤늦은 출발 인식
> 
> - AI 대학원 설립이 2026년에야 본격 추진되었으며, 평의원회 검토(2026.3)
>   […중략…]
>   밀린다"는 전제의 사실 여부와 그 원인을 판단할 수 없습니다. 다만 자료가 보여주는 것은, 서울대 내부에서도 AI 전담 대학원·인프라·가이드라인 등이 **2025~2026년에야 본격적으로 구축되기 시작**했다는 점이며, 복수의 거버넌스 기구를 거쳐야 하는 의사결정 구조가 속도 측면에서 내부적으로도 인식되고 있다는 점입니다.
> 
> KAIST와의 비교 분석이 필요하시다면, 양 기관의 공식 연구성과 데이터나 외부 평가 보고서를 함께 참고하시길 권합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [56] 모델: `external-needed`  ·  67자 · tier1 · 위키: vision, plan, history, status

**Q:** 서울대의 국제 경쟁력 지표에서 강점과 약점은 무엇이며, 주요 글로벌 대학과 비교했을 때 개선이 필요한 영역은 어디인가요?

**평가자 aspect 판정:**
  - 서울대의 국제 경쟁력 지표(순위·평가점수 등) **[no]**
  - 서울대의 국제 경쟁력 강점 영역 **[partial]**
  - 서울대의 국제 경쟁력 약점 영역 **[partial]**
  - 주요 글로벌 대학과의 비교 분석 **[no]**

**부족(missing):** 구체적 국제 경쟁력 지표(QS·THE·ARWU 등 세계대학순위, 국제화지수 수치) · 서울대 vs. 하버드·옥스포드·칭화·도쿄대 등 글로벌 대학 간 비교 평가 · 현황 진단용 외부 평가기관 자료(언론·국제평가기구 보도)

**실제 봇 답변(발췌):**
> # 서울대학교 국제 경쟁력: 강점·약점·개선 과제
> 
> ---
> 
> ## 📊 현재 글로벌 위상
> 
> 2025/2026년 기준 서울대학교의 세계 랭킹은 다음과 같습니다.
> 
> | 평가기관 | 아시아 순위 | 세계 순위 |
> |---|---|---|
> | QS | 18위 | 38위 |
> | THE | 15위 | 58위 |
> 
> [대학현황] 현황.fact
> 
> 두 주요 평가기관에서 **세계 상위 40~60위권**을 유지하고 있으나, 아시아 내에서도 15~18위 수준으로 아시아 최상위권과는 격차가 존재합니다.
> 
> ---
> 
> ## 💪 강점 영역
> 
> ### 1. 연구·교류 네트워크 규모
> 국제 학술교류 협정 규모는 상당합니다.
> - 본부 기준: **59개국 321개 기관** (학술교류), **46개국 268개 기관** (학생교환) [대학현황] 현황.fact
> - 대학(원) 기준: **72개국 708개 기관** (학술교류), **40개국 369
>   […중략…]
>   넌스입니다. 특히 중장기발전계획과 대학운영계획이 **일관되게** 질적 국제화로의 전환 필요성을 강조한다는 점에서 (두 위키에서 교차 확인되므로 신뢰도 높음), 이 영역이 가장 시급한 개선 과제로 판단됩니다.
> 
> > **자료 범위 한계**: 개별 대학(하버드, MIT, 도쿄대 등)과의 직접 수치 비교 데이터는 제공된 위키 자료에 포함되어 있지 않습니다. QS·THE 순위 외의 세부 평가 항목별 점수도 자료에 없어 항목별 비교는 제시하지 않았습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [57] 모델: `internal-gap`  ·  241자 · tier1 · 위키: senate, board, plan, finance, vision, history, status

**Q:** 서울대학교 자산 중 서울사대부속초등학교, 부속여자중학교, 부속고등학교가 있어. 사대부초, 부여중은 대학로에 있고, 사대부고는 고려대학교 근처에 있어. 이 학교들은 운동장을 갖고 있는데 요새 현대식 학교들은 운동장 땅을 건물로 지어서 실내 체육관으로 운동장 활용을 대신하고 있어. 사대부속 학교들의 부동산을 고층건물로 짓고 일부 저층은 원래 초중고등학교 용도로, 나머지 건물 고층부는 대학교의 교육 연구시설로 사용하는 것은 가능할까?

**평가자 aspect 판정:**
  - 서울대 부속학교(사대부초, 부여중, 사대부고)의 현재 위치 및 보유 부동산 **[no]**
  - 부속학교 운동장의 현재 상태 및 시설 구성 **[no]**
  - 부속학교 부동산을 고층건물로 개발하는 것의 법적/제도적 가능성 **[no]**
  - 저층을 교육용, 고층을 연구시설로 혼합 사용하는 방안의 실현 가능성 또는 선례 **[no]**

**부족(missing):** 서울대 부속학교 현황 및 부동산 보유 현황 · 부속학교 시설 개발 계획 또는 논의 기록 · 교육용 부동산의 복합개발 또는 혼합사용 관련 규정·방침 · 학교 운동장 대체시설(실내체육관) 도입 현황

**실제 봇 답변(발췌):**
> # 서울대 사대부속학교 부지 고층 복합개발 가능성 분석
> 
> ---
> 
> ## 🔑 핵심 결론 먼저
> 
> > **제공된 자료에는 사대부속학교(사대부초·부여중·사대부고) 부지의 구체적 현황, 면적, 개발 가능성에 대한 직접적 자료가 없습니다.** 다만 서울대의 자산 운용 전략, 부동산 규제 구조, 거버넌스 의사결정 체계에 관한 자료를 바탕으로 **가능성과 장애물을 구조적으로 분석**할 수 있습니다.
> 
> ---
> 
> ## 📍 사대부속학교의 서울대 내 위상
> 
> 서울대 조직도상 부설학교는 별도의 거버넌스 체계를 갖습니다 [대학현황 서울대학교 조직도 개요](/wiki?agent=status&type=facts&id=%EC%A1%B0%EC%A7%81%EB%8F%84-%EA%B0%9C%EC%9A%94.fact):
> 
> - **심의기구**: 정관 규정에 **"부설학교 교원인사위원회"** 와 **"부설학교 발전운영위원회"** 가 독립
>   […중략…]
>    가능한 방식입니다.
> 
> ---
> 
> ## ⚠️ 분석의 한계
> 
> 제공된 자료에는 **사대부속학교 3개교의 부지 면적·현황·개발 제한 조건·용도지역·현재 시설 노후도**에 대한 구체적 데이터가 포함되어 있지 않습니다. 위 분석은 서울대의 자산·재정·거버넌스 구조에서 **구조적으로 유추**한 것으로, 실제 개발 가능성 판단을 위해서는 **서울시 도시계획 정보, 각 학교 부지의 용도지역 지정 현황, 교육청과의 협의 가능성**에 대한 별도 조사가 필요합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [58] 모델: `internal-gap`  ·  101자 · tier1 · 위키: senate, board, plan, history, status, vision, finance

**Q:** 서울대 예산의 비중을 각 항목 별로 알려줘. 고정성 예산과 비고정성 예산을 나눠주고, 서울대가 새로운 대학 운영을 위해 가용한 유동성 있는 예산의 규모를 추산할 수 있도록 분류해줘.

**평가자 aspect 판정:**
  - 서울대 전체 예산의 항목별 비중(세부 구성) **[no]**
  - 고정성 예산과 비고정성 예산의 분류 및 규모 **[no]**
  - 대학 운영을 위해 가용한 유동성 있는 예산의 규모 추산 **[no]**
  - 예산 분류 방법론(어떤 항목이 고정/비고정인지) **[no]**

**부족(missing):** 법인회계 예산의 항목별 세부 내역 및 비중 · 고정성/비고정성 예산의 분류 기준 · 유동성 있는 예산 규모 산출 자료 · 예산 편성 구조(세입·세출 항목 분류)

**실제 봇 답변(발췌):**
> # 서울대학교 법인회계 예산 구조 분석
> ## — 고정성·비고정성 분류 및 유동 가용 예산 추산
> 
> ---
> 
> ## 📊 1. 2026년도 세출 예산 항목별 비중 (전체 구조)
> 
> | 항목 | 2026(안) 금액(억원) | 전체比(%) | 고정성 여부 |
> |---|---:|---:|---|
> | 인건비 | 4,860 | 40.4% | 🔒 고정성 |
> | 수입대체/책임운영경비 | 1,237 | 10.3% | 🔒 고정성 (수익연동) |
> | 운영비(대학기본) | 726 | 6.0% | 🔒 준고정성 |
> | 운영비(대학원) | 318 | 2.6% | 🔒 준고정성 |
> | 부설학교 | 292 | 2.4% | 🔒 준고정성 |
> | 보조금 | 284 | 2.4% | 🔒 준고정성 |
> | 예비비 | 20 | 0.2% | △ 반유동 |
> | 적립금 | 169 | 1.4% | △ 반유동 |
> | **사업비** | **4,301** | 
>   […중략…]
>   
> 1. **사업비 내부 구성** (계속/신규 구분)은 제공된 자료 범위에 세부 명세가 없어 정밀 추산이 어렵습니다.
> 2. 산학협력단(2024년 약 1조 규모) 및 발전재단(약 3,900억) 예산은 **법인회계와 별도 운영**되므로 위 분석에 포함되지 않았습니다 [재무정보공시] 주체별-운영수익.fact.
> 3. 세입 측면(정부출연금·등록금·기부금 변동)이 사업비 가용 규모를 직접 제약하므로, 세입 구조 분석을 병행하면 더 정밀한 추산이 가능합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [59] 모델: `internal-gap`  ·  86자 · tier1 · 위키: senate, board, plan, vision, status

**Q:** 시기적으로 동시에 공고가 나고, 같은 기간 동안 인터뷰를 끝내야 하며, 사전에 정한 기간 내에 임용 결정을 내려야 하는 경직된 시스템에 대한 불만은 없나?

**평가자 aspect 판정:**
  - 교원 임용 공고·면접·임용결정 시기의 경직성에 대한 불만 존재 여부 **[no]**
  - 동시 공고, 동일 기간 면접, 사전 정한 기간 내 임용결정 시스템에 대한 구체적 논의 기록 **[no]**
  - 해당 임용 프로세스의 경직된 구조에 대한 평의원회 의견·요청·지적 **[no]**
  - 교원 임용 절차의 유연성·개선 필요성 관련 거버넌스 기록 **[no]**

**부족(missing):** 교원 임용 공고 시기 동시성에 대한 논의 · 면접 일정 통일에 대한 불만·지적 · 임용결정 기한 경직성에 대한 평의원회 의견 · 교원 채용 프로세스 개선 요청·제안

**실제 봇 답변(발췌):**
> ## 신임교원 임용 일정의 경직성에 대한 불만 여부
> 
> 제공된 자료 전체를 검토한 결과, **"동시 공고 → 동일 인터뷰 기간 → 사전 확정 기간 내 임용 결정"이라는 경직된 임용 일정 시스템에 대한 불만이나 논의**는 현재 제공된 위키 자료 범위 내에 존재하지 않습니다.
> 
> ---
> 
> ### 📋 자료에서 확인되는 교원 임용 관련 논의
> 
> 자료에는 임용 **일정의 경직성**이 아닌, 다음과 같이 다른 측면의 논의들이 존재합니다.
> 
> | 논의 주제 | 내용 | 출처 |
> |---|---|---|
> | 교원 성과 중시 연봉제 | 정년보장교원 대상 연봉제 적용 원칙화, 우수 인력 확보를 위한 연봉 책정 특례 추가 | [이사회] 2025-3차 |
> | 겸임교원 임용 규정 | 정년퇴직 교원 재임용 제한 단서조항 삭제, 객원교원 임무 추가에 대한 우려 | [평의원회] 18기-14차 |
> | 새로운 형태의 교원 임용 | 중
>   […중략…]
>    촉구 | [평의원회] 18기-16차 |
> 
> ---
> 
> ### ⚠️ 한계
> 
> 질문에서 전제하는 **"동시 공고·동일 인터뷰 기간·사전 확정 기간 내 임용 결정"이라는 경직된 시스템의 존재 여부** 자체가 제공된 자료에서 확인되지 않으며, 이에 대한 구성원의 불만이나 평의원회·이사회 차원의 논의 역시 자료 범위 밖에 있습니다. 해당 사안은 교원인사위원회 내부 운영 절차에 해당할 가능성이 높으나, 관련 자료가 현재 제공된 위키에 포함되어 있지 않습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [60] 모델: `internal-gap`  ·  36자 · tier1 · 위키: senate, vision, status, yhl-speeches

**Q:** 인문대학 관점과 사회과학대학 관점에서 거버넌스에 대한 입장 차이?

**평가자 aspect 판정:**
  - 인문대학의 거버넌스 관점·입장 **[no]**
  - 사회과학대학의 거버넌스 관점·입장 **[no]**
  - 두 단과대학 간 거버넌스 관련 입장 차이 또는 충돌 사례 **[no]**
  - 거버넌스 정의·개념·철학에 대한 학파별/학제별 입장 **[no]**

**부족(missing):** 인문대학의 거버넌스에 대한 입장 · 사회과학대학의 거버넌스에 대한 입장 · 두 대학 간 거버넌스 관점의 구체적 차이 · 학제적 거버넌스 해석의 차이

**실제 봇 답변(발췌):**
> 제공된 자료에는 인문대학 또는 사회과학대학이 거버넌스 현안에 대해 각각 어떤 입장을 취했는지를 보여주는 단과대학 단위의 입장 자료가 포함되어 있지 않습니다.
> 
> 다만, 제공된 자료에서 인문대학 관련 인물로는 **강창우** 교수가 중장기발전계획위원회 멀티캠퍼스 분과 공동위원장으로, **안지현** 평의원이 17기 운영위원회 위원으로 언급되며 [17기-12차], 사회과학대학 관련 인물로는 별도 거버넌스 입장 자료가 확인되지 않습니다.
> 
> 단과대학별 거버넌스 입장 비교를 원하신다면, 평의원회 회의록에서 각 단과대학 소속 평의원의 발언을 중심으로 질문해 주시면 더 구체적인 답변이 가능합니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [61] 모델: `internal-gap`  ·  33자 · tier1 · 위키: senate, board, plan, status, yhl-speeches, vision

**Q:** 신문컬럼 등 자료를 크롤링하여 학습할 수 있는 방법 없을까?

**평가자 aspect 판정:**
  - 신문컬럼 등 자료를 크롤링하여 학습할 수 있는 구체적 방법론·기술·플랫폼 **[no]**
  - 서울대학교 자체의 크롤링·데이터 수집 관련 정책·규정·지침 **[no]**
  - 서울대학교 내 크롤링·자동수집 사업 추진 사례 **[no]**

**부족(missing):** 신문컬럼 크롤링 방법 · 데이터 수집 기술·도구 · 서울대 크롤링·자료수집 정책 · 관련 추진 사례

**실제 봇 답변(발췌):**
> 이 질문은 제공된 위키 자료(평의원회, 이사회, 대학운영계획, 대학현황, 유홍림총장연설, 중장기발전계획)의 범위를 벗어난 기술적·방법론적 질문입니다.
> 
> 저는 서울대학교 거버넌스 통합 위키 AI 어시스턴트로서, 위에 제공된 위키 자료를 바탕으로 서울대학교 관련 질문에만 답변할 수 있습니다.
> 
> ---
> 
> **신문 칼럼 크롤링 및 위키 자료 확장과 관련된 문의**는 위키 운영팀이나 시스템 관리자에게 직접 문의해 주시기 바랍니다.
> 
> 서울대학교 거버넌스, 운영계획, 재정, 역사 등 위키 자료 범위 내의 질문이 있으시면 언제든지 도와드리겠습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [62] 모델: `internal-gap`  ·  33자 · tier1 · 위키: senate, board, plan, status, yhl-speeches, vision

**Q:** 세부 내용 미확인이라고 답변한 회의들에 대해서 자세히 알려줘

**평가자 aspect 판정:**
  - 세부 내용 미확인이라고 명시된 회의 식별 **[no]**
  - 해당 회의들의 구체적 내용·쟁점·의사결정 사항 **[no]**
  - 미확인 사유·배경 **[no]**

**부족(missing):** "세부 내용 미확인"이라는 표현이 명시된 회의 목록 · 그러한 회의들의 구체적 안건·쟁점·결과 · 미확인 이유 및 향후 보충 계획

**실제 봇 답변(발췌):**
> 죄송합니다만, 질문의 맥락을 정확히 파악하기 어렵습니다.
> 
> "세부 내용 미확인이라고 답변한 회의들"이란 표현은 **이전 대화에서 제가 특정 회의들에 대해 "확인되지 않는다"고 답변한 경우를 가리키는 것**으로 보입니다.
> 
> 그런데 현재 대화 기록상 **이전에 그런 답변을 드린 내역이 없습니다.** 이 질문이 이번 대화의 첫 번째 질문이기 때문입니다.
> 
> ---
> 
> ## 도움을 드리기 위해 확인이 필요합니다
> 
> 다음 중 어떤 경우인지 알려주시면 정확한 답변을 드릴 수 있습니다:
> 
> 1. **다른 대화 세션**에서 제가 "확인되지 않는다"고 답한 회의들을 말씀하시는 경우
>    → 해당 회의명·기수·차수를 직접 알려주시면 현재 제공된 자료 내에서 확인해 드립니다.
> 
> 2. **특정 기수·차수 범위**의 회의록 전체를 조회하고 싶으신 경우
>    → 예: "17기 전체 회의 요약", "18기 주요 안건" 등으로 질문해 주시면 됩니다.
> 
> 3. **특정 주제**(예: 첨단융합학부, 총장선출, 예산 등)에 대해 어떤 회의에서 논의됐는지 알고 싶으신 경우
>    → 주제를 알려주시면 관련 회의를 정리해 드립니다.
> 
> 어떤 회의 또는 주제에 대해 알고 싶으신지 구체적으로 말씀해 주세요!

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [63] 모델: `internal-gap`  ·  32자 · tier1 · 위키: board, plan, status, senate, history

**Q:** 이석재 후보의 공약 중 이공계 학생에게 관련 있는 내용은?

**평가자 aspect 판정:**
  - 이석재 후보의 공약 내용 **[no]**
  - 이공계 학생 관련 공약 **[no]**

**부족(missing):** 이석재의 공약(manifesto) 또는 정책 제안 자료 · 이공계 학생 대상 정책·공약 내용

**실제 봇 답변(발췌):**
> # 이석재 후보 공약 중 이공계 학생 관련 내용
> 
> ## 🔬 연구 기회 확대 — 공동 연구자 지위
> 
> 이석재 후보는 대학원생, 특히 이공계 박사과정생을 "값싼 연구 노동력"이 아닌 **"전업 공동 연구자"**로 대우해야 한다고 명시합니다.
> 
> > "이제는 석·박사 과정 학생들을 '값싼 연구 노동력을 제공하는 주체'나 '파트타임'으로 여기는 관점에서 완전히 벗어나, '함께 전업으로 공부하는 공동 연구자'로 대우해야 하는 시점이 왔습니다."
> > — [이석재 후보-stance] 학문후속세대지원
> 
> 이는 이공계 연구실 문화에 직접적으로 적용되는 발언입니다. 도제식 관계 철폐, 잡무 금지, 경력개발 기구 창설을 제안하며, 모든 박사과정생에게 **등록금 + 월 150만원 생활비**를 보장하는 것을 목표로 합니다. [이석재 후보-stance] 학문후속세대지원
> 
> 현재 서울대의 기초학문분야 지원(박사 연 2,600만원
>   […중략…]
>   전공 교육 커리큘럼 | 이공계 교육과정 혁신 | [이석재 후보-stance] AI시대대학역할 |
> | AI-인간 문제 연구소 설립 | 새로운 연구 분야 창출 | [이석재 후보-stance] AI시대대학역할 |
> | AI·생명과학·반도체·우주 4대 이니셔티브 | 이공계 장기 연구 방향 제시 | [이석재 후보-stance] 중장기연구이니셔티브 |
> | 스탠퍼드·막스플랑크 파트너십 | 이공계 국제공동연구 기회 | [이석재 후보-stance] 국제화전략 |

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

## [64] 모델: `internal-gap`  ·  27자 · tier1 · 위키: board, vision, senate, status, plan, history

**Q:** 이사회에서 부결된 안건들은 어떤 것들이 있었나요?

**평가자 aspect 판정:**
  - 이사회에서 부결된 안건의 구체적 사례 및 목록 **[no]**
  - 부결 안건의 이유/배경 **[no]**
  - 부결 안건의 처리 결과(재상정 여부 등) **[no]**

**부족(missing):** 이사회 부결 안건 관련 정보 전무 · 2023~2026년 이사회 회의록에서 '부결' 결과를 가진 안건 기록 없음 · 모든 의결 결과가 '원안 의결', '전원 찬성', '원안 추인', '보류', '보고 접수' 등으로만 기록되어 있으며, 부결(否決) 사항은 없음

**실제 봇 답변(발췌):**
> # 이사회에서 부결된 안건
> 
> ## ⚖️ 핵심 결론
> 
> 제공된 이사회 자료 전체를 검토한 결과, **이사회에서 명시적으로 표결 부결된 안건은 확인되지 않습니다.**
> 
> ---
> 
> ## 📋 확인된 이사회 심의 패턴
> 
> 제공된 자료에서 이사회 안건들은 대부분 다음 두 가지 형태로 처리되었습니다:
> 
> | 처리 유형 | 사례 | 출처 |
> |---|---|---|
> | **원안 의결** | 예산·결산·이사장 선출·학칙 추인 등 대다수 안건 | [이사회] 2023-1차 ~ 2026-2차 |
> | **보류 후 소위원회 위임** | 임원 보수지침·총장 성과평가 지표 제정(안) — "총장 보수 인상 필요성은 인정하되 소위원회를 구성하여 추후 결정" | [이사회] 2023-1차 |
> | **상정 철회** | 정관 개정(안) — 표결 전 자진 철회 | [이사회] 2024-2차 |
> 
> ---
> 
> ## ⚠️ 유의사항
> 
> - **부결 ≠ 철
>   […중략…]
>   2차 등)는 상세 안건 내용 없이 헤더만 제공되어 있어 해당 회의의 전체 처리 결과를 완전히 확인할 수 없습니다.
> 
> ---
> 
> ## 🔍 시사점
> 
> 부결 사례가 없다는 점은 이사회의 **높은 의결 효율성**을 보여주는 동시에, 중장기발전계획이 지적한 **"이사회 개방성 제고"** 과제 [중장기발전계획] 중장기-제2장-운영체제 와 연결하여 보면, 이사회가 충분한 내부 검토와 합의를 거쳐 안건을 상정하는 구조적 특성을 반영한 것으로 해석할 수 있습니다.

**gold:** ``         ← 맞으면 비워두기 / 틀리면 answerable·opinion-grounded·external-needed·internal-gap 중 하나

---

